import type { AdminMe, MemberPermissions } from "@/api/contracts";

const permission = (feature: string, action: string) => `platform.${feature}.${action}` as const;

export const adminPermissions = {
  accessOverview: permission("admin_users", "overview"),
  usersRead: permission("admin_users", "read"),
  usersCreate: permission("admin_users", "create"),
  usersMutate: permission("admin_users", "toggle_active"),
  usersRename: permission("admin_users", "rename"),
  usersChangeEmail: permission("admin_users", "change_email"),
  usersSendEmailVerification: permission("admin_users", "send_email_verification"),
  usersReadPermissions: permission("admin_users", "read_permissions"),
  usersBulkSetActive: permission("admin_users", "bulk_set_active"),
  usersBulkAssignRole: permission("admin_users", "bulk_assign_role"),
  usersBulkResendActivation: permission("admin_users", "bulk_resend_activation"),
  usersResendActivation: permission("admin_users", "resend_activation"),
  usersTemporaryAccess: permission("admin_users", "generate_temporary_access"),
  usersAssignRole: permission("admin_users", "assign_role"),
  usersRemoveRole: permission("admin_users", "remove_role"),
  rolesRead: permission("roles", "read"),
  rolesReadDetail: permission("roles", "read_detail"),
  rolesCreate: permission("roles", "create"),
  rolesUpdate: permission("roles", "update"),
  rolesMutate: permission("roles", "toggle_active"),
  rolesBulkSetActive: permission("roles", "bulk_set_active"),
  rolesReadHolders: permission("roles", "read_holders"),
  rolesReadHistory: permission("roles", "read_history"),
  rolesListPresets: permission("roles", "list_presets"),
  rolesListGrantable: permission("roles", "list_grantable_permissions"),
  rolesPreviewImpact: permission("roles", "preview_impact"),
  rolesGrant: permission("roles", "grant_permission"),
  rolesRevoke: permission("roles", "revoke_permission"),
  rolesCreateFromPreset: permission("roles", "create_from_preset"),
  rolesDuplicate: permission("roles", "duplicate"),
  rolesReplacePermissions: permission("roles", "replace_permissions"),
  rolesTransitionStatus: permission("roles", "transition_status"),
  rolesDelete: permission("roles", "delete"),
  plansOverview: permission("plans", "overview"),
  plansList: permission("plans", "list"),
  plansReadDetail: permission("plans", "read_detail"),
  plansListFeatures: permission("plans", "list_features"),
  plansListSubscribers: permission("plans", "list_subscribers"),
  plansLookupSubscriberOwnerEmail: permission("plans", "lookup_subscriber_owner_email"),
  plansPreviewDelete: permission("plans", "preview_delete"),
  plansCreate: permission("plans", "create"),
  plansUpdate: permission("plans", "update"),
  plansDuplicate: permission("plans", "duplicate"),
  plansRevise: permission("plans", "revise"),
  plansTransition: permission("plans", "transition_status"),
  plansDelete: permission("plans", "delete"),
  plansAssignFeature: permission("plans", "assign_feature"),
  plansUpdateFeature: permission("plans", "update_feature"),
  plansRemoveFeature: permission("plans", "remove_feature"),
  addOnsList: permission("plans", "list_add_ons"),
  addOnsReadDetail: permission("plans", "read_add_on"),
  addOnsCreate: permission("plans", "create_add_on"),
  addOnsUpdate: permission("plans", "update_add_on"),
  addOnsRevise: permission("plans", "revise_add_on"),
  addOnsTransition: permission("plans", "transition_add_on"),
  addOnsDelete: permission("plans", "delete_add_on"),
  addOnsAssignFeature: permission("plans", "assign_add_on_feature"),
  addOnsUpdateFeature: permission("plans", "update_add_on_feature"),
  addOnsRemoveFeature: permission("plans", "remove_add_on_feature"),
  quotaPackagesList: permission("plans", "list_quota_packages"),
  quotaPackagesReadDetail: permission("plans", "read_quota_package"),
  quotaPackagesCreate: permission("plans", "create_quota_package"),
  quotaPackagesUpdate: permission("plans", "update_quota_package"),
  quotaPackagesTransition: permission("plans", "transition_quota_package"),
  quotaPackagesDelete: permission("plans", "delete_quota_package"),
  subscriptionsRead: permission("subscriptions", "read"),
  subscriptionsSearch: permission("subscriptions", "search_accounts"),
  subscriptionsCreate: permission("subscriptions", "create"),
  subscriptionsCreateTrial: permission("subscriptions", "create_trial"),
  subscriptionsOverrides: permission("subscriptions", "update_overrides"),
  subscriptionsReadChanges: permission("subscriptions", "read_changes"),
  subscriptionsConfirmCheckout: permission("subscriptions", "confirm_checkout"),
  registryRead: permission("registry", "read"),
  registryFeatureCatalog: permission("registry", "feature_catalog"),
  registryPermissionCatalog: permission("registry", "permission_catalog"),
  registryControlHistory: permission("registry", "control_history"),
  registrySync: permission("registry", "sync_status"),
  registryPublicVisibility: permission("registry", "update_public_visibility"),
  registryNewSales: permission("registry", "update_new_sales"),
  registryNewGrants: permission("registry", "update_new_grants"),
  registryRuntime: permission("registry", "update_emergency_runtime"),
} as const;

export const clientPermissions = {
  workspaceRead: permission("workspace", "read"),
  workspaceDelete: permission("workspace", "delete"),
  companiesRead: permission("company", "read_all"),
  companyDetailRead: permission("company", "read_single"),
  companiesCreate: permission("company", "create"),
  companiesUpdate: permission("company", "update"),
  companiesDelete: permission("company", "delete"),
  companiesReactivate: permission("company", "reactivate"),
  organizationRead: permission("organization", "list_groups"),
  organizationCreate: permission("organization", "create"),
  organizationUpdate: permission("organization", "update"),
  organizationMove: permission("organization", "move"),
  organizationReorder: permission("organization", "reorder"),
  organizationArchive: permission("organization", "archive"),
  organizationRestore: permission("organization", "restore"),
  organizationDelete: permission("organization", "delete"),
  organizationListMemberships: permission("organization", "list_memberships"),
  organizationListMemberPlacements: permission("organization", "list_member_placements"),
  organizationPutMember: permission("organization", "put_membership"),
  organizationRemoveMember: permission("organization", "remove_membership"),
  organizationCreateTemplate: permission("organization", "create_template"),
  organizationListTemplates: permission("organization", "list_templates"),
  organizationPreviewTemplate: permission("organization", "preview_template"),
  organizationInstantiateTemplate: permission("organization", "instantiate_template"),
  organizationDeleteTemplate: permission("organization", "delete_template"),
  membersRead: permission("staff", "read"),
  membersReadAccess: permission("staff", "read_access"),
  membersReadAuthorization: permission("staff", "read_authorization"),
  membersReadOverrides: permission("staff", "read_overrides"),
  membersCreate: permission("staff", "create"),
  membersUpdate: permission("staff", "update"),
  membersDeactivate: permission("staff", "delete"),
  membersReactivate: permission("staff", "reactivate"),
  membersAssignRole: permission("staff", "assign_role"),
  membersRemoveRole: permission("staff", "remove_role"),
  membersGrantPermission: permission("staff", "grant_permission"),
  membersRevokePermission: permission("staff", "revoke_permission"),
  membersRegenerateAccess: permission("staff", "regenerate_access"),
  membersResetAccess: permission("staff", "reset_access"),
  membersUnlockAccess: permission("staff", "unlock_access"),
  rolesRead: permission("rbac", "view"),
  roleDetailRead: permission("rbac", "read"),
  rolesImpact: permission("rbac", "impact"),
  rolesPermissionCatalog: permission("rbac", "permission_catalog"),
  rolesCreate: permission("rbac", "create"),
  rolesUpdate: permission("rbac", "update"),
  rolesDelete: permission("rbac", "delete"),
  rolesGrant: permission("rbac", "grant"),
  rolesRevoke: permission("rbac", "revoke"),
  rolesActivate: permission("rbac", "activate"),
  rolesDeactivate: permission("rbac", "deactivate"),
  rolesArchive: permission("rbac", "archive"),
  rolesDuplicate: permission("rbac", "duplicate"),
  collaborationsRead: permission("b2b", "view"),
  collaborationDetailRead: permission("b2b", "read_detail"),
  incomingCollaborationsRead: permission("b2b", "view_incoming"),
  collaborationsRequest: permission("b2b", "request"),
  collaborationsResolveShareCode: permission("b2b", "resolve_share_code"),
  collaborationsAccept: permission("b2b", "accept"),
  collaborationsReject: permission("b2b", "reject"),
  collaborationsCancelRequest: permission("b2b", "cancel_request"),
  collaborationsSuspend: permission("b2b", "suspend"),
  collaborationsResume: permission("b2b", "resume"),
  collaborationsRevoke: permission("b2b", "revoke"),
  collaborationsGrant: permission("b2b", "grant_permission"),
  collaborationsRevokeGrant: permission("b2b", "revoke_permission"),
  collaborationsReadPermissions: permission("b2b", "read_permissions"),
  collaborationsPermissionCatalog: permission("b2b", "permission_catalog"),
  collaborationsReadShareCode: permission("b2b", "read_share_code"),
  collaborationsManageShareCode: permission("b2b", "manage_share_code"),
  collaborationsRegenerateShareCode: permission("b2b", "regenerate_share_code"),
  subscriptionRead: permission("subscription", "read"),
  subscriptionCatalog: permission("subscription", "catalog"),
  subscriptionPreview: permission("subscription", "preview"),
  subscriptionApply: permission("subscription", "apply"),
  subscriptionReadChanges: permission("subscription", "read_changes"),
  subscriptionCancel: permission("subscription", "cancel_change"),
} as const;

/**
 * The subscription screen contains three independently guarded read surfaces. Keeping this list
 * shared prevents the route and navigation from silently making `subscription.read` a prerequisite
 * for the separately authorized catalog and change-history endpoints.
 */
export const clientSubscriptionSurfacePermissions = [
  clientPermissions.subscriptionRead,
  clientPermissions.subscriptionCatalog,
  clientPermissions.subscriptionReadChanges,
] as const;

/** Each overview card family is independently readable, including registry sync on its own. */
export const adminOverviewSurfacePermissions = [
  adminPermissions.accessOverview,
  adminPermissions.plansOverview,
  adminPermissions.registrySync,
] as const;

export function adminProfileCan(
  profile: Pick<AdminMe, "isSuperAdmin" | "permissions"> | null | undefined,
  required: string,
) {
  return Boolean(profile?.isSuperAdmin || profile?.permissions.includes(required));
}

export function clientProfileCan(
  profile: Pick<MemberPermissions, "isOwner" | "permissions"> | null | undefined,
  required: string,
) {
  return Boolean(profile?.isOwner || profile?.permissions.includes(required));
}
