package com.hiveapp.platform.client.plan.service.impl;

import com.hiveapp.platform.admin.domain.entity.AdminUser;
import com.hiveapp.platform.admin.domain.repository.AdminUserRepository;
import com.hiveapp.platform.admin.service.AdminMutationAuthorizer;
import com.hiveapp.platform.client.plan.domain.constant.*;
import com.hiveapp.platform.client.plan.domain.entity.*;
import com.hiveapp.platform.client.plan.domain.repository.*;
import com.hiveapp.platform.client.plan.dto.*;
import com.hiveapp.platform.client.plan.service.*;
import com.hiveapp.platform.client.account.service.AccountDirectoryService;
import com.hiveapp.platform.client.account.dto.AccountDirectoryEntryDto;
import com.hiveapp.platform.registry.definition.*;
import com.hiveapp.platform.registry.definition.service.PlatformControlFeatureService;
import com.hiveapp.platform.registry.service.RegistryCatalogVersionService;
import com.hiveapp.platform.registry.domain.repository.FeatureRepository;
import com.hiveapp.shared.exception.*;
import com.hiveapp.shared.audit.domain.AuditLogRepository;
import dev.karroumi.permissionizer.PermissionNode;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
@PermissionNode(key=OffersFeature.KEY,description="Commercial Offer management",guard=PermissionNode.Guard.ON)
public class CommercialOfferAdminServiceImpl extends PlatformControlFeatureService implements CommercialOfferAdminService{
 private final CommercialOfferRepository offers; private final CommercialOfferCodeReservationRepository codes;
 private final CommercialOfferLineageRepository lineages;
 private final CommercialOfferCapacityRepository capacities;private final CommercialOfferRedemptionRepository redemptions;
 private final CommercialCampaignRepository campaigns;private final ProductPriceRepository prices;
 private final PlanFeatureRepository planFeatures; private final AddOnRepository addOns;
 private final QuotaPackageRepository quotaPackages; private final CommercialCatalogResolver catalogResolver;
 private final AdminUserRepository admins;private final AdminMutationAuthorizer authorizer;
 private final CommercialCatalogVersionService catalogVersions;private final RegistryCatalogVersionService registryVersions;
 private final CommercialPreviewTokenService previewTokens;private final Clock clock;
 private final CommercialOfferCodeHasher codeHasher;
 private final AccountDirectoryService accountDirectoryService;
 private final CommercialOfferService commercialOfferService;
 private final AuditLogRepository auditLogRepository;
 private final FeatureRepository featureRepository;
 @Override protected FeatureDefinition featureDefinition(){return OffersFeature.definition();}

 @Override @Transactional(readOnly=true) @PermissionNode(key="list",description="List Offers")
 public Page<CommercialOfferViews.Summary> list(String search,CommercialOfferStatus status,boolean archived,Pageable p){Specification<CommercialOffer>s=(r,q,c)->{var ps=new ArrayList<jakarta.persistence.criteria.Predicate>();if(!archived&&status!=CommercialOfferStatus.ARCHIVED)ps.add(c.notEqual(r.get("status"),CommercialOfferStatus.ARCHIVED));if(status!=null)ps.add(c.equal(r.get("status"),status));if(search!=null&&!search.isBlank()){String x="%"+search.trim().toLowerCase(Locale.ROOT).replace("%","\\%").replace("_","\\_")+"%";ps.add(c.or(c.like(c.lower(r.get("name")),x,'\\'),c.like(c.lower(r.get("lineage").get("businessCode")),x,'\\')));}return c.and(ps.toArray(jakarta.persistence.criteria.Predicate[]::new));};return offers.findAll(s,bounded(p)).map(this::summary);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="read",description="Read Offer") public CommercialOfferViews.Detail get(UUID id){return detail(require(id));}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="create",description="Create Offer draft") public CommercialOfferViews.Detail create(CommercialOfferRequests.Create r){var campaign=requireCampaign(r.campaignId());var owner=currentOwner();var lineage=lineages.saveAndFlush(CommercialOfferLineage.create(nextCode(r.name()),campaign,r.discovery(),r.acceptance(),codeHasher.hash(r.customerCode()),r.globalLimit(),r.perAccountLimit(),owner));var o=CommercialOffer.draft(lineage,r.name(),r.description(),r.startsAt(),r.endsAt(),r.selection(),r.effects());validateSelection(o);try{o=offers.saveAndFlush(o);capacities.saveAndFlush(CommercialOfferCapacity.create(o.getLineageId()));return detail(o);}catch(DataIntegrityViolationException e){throw new InvalidStateException("Offer changed concurrently; reload and retry.");}}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="update",description="Update Offer draft") public CommercialOfferViews.Detail update(UUID id,CommercialOfferRequests.Update r){var o=lock(id);version(o,r.version());translate(()->o.edit(r.name(),r.description(),r.startsAt(),r.endsAt(),r.selection(),r.effects()));if(r.lineageTerms()!=null){if(o.getRevisionNumber()!=1||codes.findByLineageId(o.getLineageId()).isPresent())throw new InvalidStateException("Published Offer lineage terms are immutable.");var t=r.lineageTerms();String hash=switch(t.customerCodeChange().mode()){case KEEP->o.getCustomerCodeHash();case REMOVE->null;case REPLACE->{if(t.customerCodeChange().value()==null||t.customerCodeChange().value().isBlank())throw new InvalidRequestException("Replacement customer code is required.");yield codeHasher.hash(t.customerCodeChange().value());}};o.getLineage().editBeforeFirstPublication(t.discovery(),t.acceptance(),hash,t.globalLimit(),t.perAccountLimit());}validateSelection(o);offers.flush();return detail(o);}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="duplicate",description="Duplicate Offer") public CommercialOfferViews.Detail duplicate(UUID id,CommercialOfferRequests.Duplicate r){var src=lock(id);version(src,r.version());var lineage=lineages.saveAndFlush(CommercialOfferLineage.create(nextCode(r.name()),src.getCampaign(),src.getDiscovery(),src.getAcceptance(),null,src.getGlobalLimit(),src.getPerAccountLimit(),currentOwner()));var copy=offers.saveAndFlush(src.duplicate(lineage,r.name()));capacities.saveAndFlush(CommercialOfferCapacity.create(copy.getLineageId()));return detail(copy);}
 @Override @Transactional(isolation=Isolation.REPEATABLE_READ) @CommercialCatalogMutation @PermissionNode(key="revise",description="Revise Offer") public CommercialOfferViews.Detail revise(UUID id,CommercialOfferRequests.VersionReason r){var src=lock(id);version(src,r.version());offers.lockLineage(src.getLineageId());try{return detail(offers.saveAndFlush(src.revise(offers.maxRevision(src.getLineageId())+1)));}catch(DataIntegrityViolationException e){throw new DraftSuccessorExistsException("An Offer draft successor already exists.");}}
 @Override @Transactional(readOnly=true) @PermissionNode(key="revisions",description="Read Offer revisions")public Page<CommercialOfferViews.Revision> revisions(UUID id,Pageable p){var o=require(id);return offers.findAllByLineage_Id(o.getLineageId(),bounded(p)).map(x->new CommercialOfferViews.Revision(x.getId(),x.getRevisionNumber(),x.getStatus(),x.getCreatedAt()));}
 @Override @Transactional(readOnly=true) @PermissionNode(key="compare",description="Compare Offer revisions")public CommercialOfferViews.Comparison compare(UUID a,UUID b){var l=require(a);var r=require(b);Set<String> changed=new LinkedHashSet<>();if(!Objects.equals(l.getName(),r.getName()))changed.add("name");if(!Objects.equals(l.getSelection(),r.getSelection()))changed.add("selection");if(!Objects.equals(l.getEffects(),r.getEffects()))changed.add("effects");if(!Objects.equals(l.getStartsAt(),r.getStartsAt())||!Objects.equals(l.getEndsAt(),r.getEndsAt()))changed.add("window");if(!Objects.equals(l.getGlobalLimit(),r.getGlobalLimit())||!Objects.equals(l.getPerAccountLimit(),r.getPerAccountLimit()))changed.add("capacity");return new CommercialOfferViews.Comparison(a,b,l.getLineageId().equals(r.getLineageId()),Set.copyOf(changed));}
 @Override @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ) @PermissionNode(key="preview_publish",description="Preview Offer publication")public CommercialOfferViews.PublicationPreview previewPublication(UUID id){var o=require(id);long catalog=catalogVersions.currentRevision();String registry=registryVersions.currentVersion();var blockers=publicationBlockers(o);Instant now=clock.instant();String fp=fingerprint(o,blockers);var evidence=previewTokens.issue(CommercialPreviewKind.COMMERCIAL_OFFER_PUBLICATION,o.getId(),o.getVersion(),authorizer.currentActorUserId(),catalog,registry,fp,now);return new CommercialOfferViews.PublicationPreview(id,o.getVersion(),blockers,evidence.evaluatedAt(),evidence.expiresAt(),evidence.token());}
 @Override @Transactional(isolation=Isolation.REPEATABLE_READ) @CommercialCatalogMutation @PermissionNode(key="publish",description="Publish reviewed Offer")public CommercialOfferViews.Detail publish(UUID id,CommercialOfferRequests.Publish r){registryVersions.lockForMutation();String registry=registryVersions.currentVersion();var o=lock(id);offers.lockLineage(o.getLineageId());long catalog=catalogVersions.currentRevision();var blockers=publicationBlockers(o);previewTokens.requireValid(r.previewToken(),CommercialPreviewKind.COMMERCIAL_OFFER_PUBLICATION,o.getId(),o.getVersion(),authorizer.currentActorUserId(),catalog,registry,fingerprint(o,blockers),StaleOfferPreviewException::new);if(r.version()!=o.getVersion())throw new StaleOfferPreviewException();if(!blockers.isEmpty())throw new InvalidStateException("Offer cannot be published: "+blockers);reserveCode(o);offers.findFirstByLineage_IdAndStatus(o.getLineageId(),CommercialOfferStatus.PUBLISHED).filter(old->!old.getId().equals(o.getId())).ifPresent(old->old.retire(clock.instant()));translate(()->o.publish(clock.instant()));offers.flush();return detail(o);}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="retire",description="Retire Offer")public CommercialOfferViews.Detail retire(UUID id,CommercialOfferRequests.VersionReason r){var o=lock(id);version(o,r.version());translate(()->o.retire(clock.instant()));offers.flush();return detail(o);}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="restore",description="Restore Offer")public CommercialOfferViews.Detail restore(UUID id,CommercialOfferRequests.VersionReason r){var o=lock(id);version(o,r.version());offers.findFirstByLineage_IdAndStatus(o.getLineageId(),CommercialOfferStatus.PUBLISHED).ifPresent(x->{throw new InvalidStateException("A published successor already occupies this Offer lineage.");});translate(o::restore);offers.flush();return detail(o);}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="archive",description="Archive Offer")public CommercialOfferViews.Detail archive(UUID id,CommercialOfferRequests.VersionReason r){var o=lock(id);version(o,r.version());translate(()->o.archive(clock.instant()));offers.flush();return detail(o);}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="delete",description="Delete Offer draft")public void deleteDraft(UUID id,CommercialOfferRequests.VersionReason r){var o=lock(id);version(o,r.version());if(o.getStatus()!=CommercialOfferStatus.DRAFT)throw new InvalidStateException("Only a draft Offer can be deleted.");offers.delete(o);offers.flush();}
 @Override @Transactional(readOnly=true) @PermissionNode(key="read_owner",description="Read Offer owner")public CommercialOfferViews.Owner owner(UUID id){var o=require(id);return new CommercialOfferViews.Owner(o.getOwner().getId(),o.getOwner().getUser().getEmail(),o.getOwner().isActive());}
 @Override @Transactional @CommercialCatalogMutation @PermissionNode(key="reassign_owner",description="Reassign Offer lineage owner")public CommercialOfferViews.Detail reassignOwner(UUID id,CommercialOfferRequests.ReassignOwner r){var o=lock(id);version(o,r.version());var owner=admins.findWithUserById(r.ownerAdminUserId()).filter(AdminUser::isActive).orElseThrow(()->new InvalidRequestException("Offer owner must be active."));o.getLineage().reassignOwner(owner);lineages.flush();return detail(o);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="read_stats",description="Read Offer outcome counts")public CommercialOfferViews.Stats stats(UUID id){var o=require(id);UUID l=o.getLineageId();return new CommercialOfferViews.Stats(redemptions.countByOfferLineageIdAndStatus(l,CommercialOfferRedemptionStatus.RESERVED),redemptions.countByOfferLineageIdAndStatus(l,CommercialOfferRedemptionStatus.APPLIED),redemptions.countByOfferLineageIdAndStatus(l,CommercialOfferRedemptionStatus.CANCELLED),redemptions.countByOfferLineageIdAndStatus(l,CommercialOfferRedemptionStatus.FAILED));}
 @Override @Transactional(readOnly=true) @PermissionNode(key="read_redemptions",description="Read Offer redemption outcomes")public Page<CommercialOfferViews.Redemption> redemptions(UUID id,Pageable p){return this.redemptions.findAllByOfferLineageId(require(id).getLineageId(),bounded(p)).map(this::redemption);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="read_redemption_identities",description="Read Offer redemption Account identities")public Page<CommercialOfferViews.RedemptionIdentity> redemptionIdentities(UUID id,Pageable p){return redemptions.findAllByOfferLineageId(require(id).getLineageId(),bounded(p)).map(r->new CommercialOfferViews.RedemptionIdentity(r.getId(),r.getAccount().getId(),r.getAccount().getName(),r.getActorUserId()));}
 @Override @Transactional(readOnly=true) @PermissionNode(key="history",description="Read Offer lineage history")public Page<CommercialOfferViews.History> history(UUID id,Pageable p){var offer=require(id);var revisionIds=offers.findAllByLineage_Id(offer.getLineageId(),PageRequest.of(0,100,Sort.by("revisionNumber"))).getContent().stream().map(x->x.getId().toString()).toList();return auditLogRepository.findAllByResourceTypeAndResourceIdIn("COMMERCIAL_OFFER_ADMIN",revisionIds,bounded(p)).map(log->new CommercialOfferViews.History(log.getOccurredAt(),log.getAction(),log.getOutcome().name(),log.getActorUserId(),null));}
 @Override @Transactional(readOnly=true) @PermissionNode(key="choose_accounts",description="Choose safe Accounts for one-Account Offer operations")public Page<AccountDirectoryEntryDto> chooseAccounts(String query,Boolean active,Pageable p){return accountDirectoryService.search(query,active,bounded(p));}
 @Override @Transactional(readOnly=true) @PermissionNode(key="resolve_account_choices",description="Resolve selected Accounts for Offer operations")public List<AccountDirectoryEntryDto> resolveAccountChoices(Collection<UUID> ids){if(ids==null||ids.isEmpty()||ids.size()>100)throw new InvalidRequestException("Between 1 and 100 Account ids are required.");return accountDirectoryService.resolve(ids);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="choose_products",description="Choose exact Offer products and prices")public Page<CommercialOfferViews.PricedChoice> chooseProducts(ProductPriceOwnerType type,String query,Pageable p){String term=query==null||query.isBlank()?null:query.trim().toLowerCase(Locale.ROOT);Specification<ProductPrice> spec=(root,q,cb)->{var predicates=new ArrayList<jakarta.persistence.criteria.Predicate>();predicates.add(cb.equal(root.get("ownerType"),type));if(term!=null){String relation=switch(type){case PLAN->"plan";case ADD_ON->"addOn";case QUOTA_PACKAGE->"quotaPackage";};String pattern="%"+term.replace("%","\\%").replace("_","\\_")+"%";predicates.add(cb.or(cb.like(cb.lower(root.get(relation).get("name")),pattern,'\\'),cb.like(cb.lower(root.get(relation).get("code")),pattern,'\\')));}return cb.and(predicates.toArray(jakarta.persistence.criteria.Predicate[]::new));};return prices.findAll(spec,bounded(p)).map(this::pricedChoice);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="resolve_product_choices",description="Resolve selected exact Offer prices")public List<CommercialOfferViews.PricedChoice> resolveProductChoices(Collection<UUID> ids){if(ids==null||ids.isEmpty()||ids.size()>100)throw new InvalidRequestException("Between 1 and 100 Price ids are required.");return prices.findAllByIdIn(ids).stream().map(this::pricedChoice).toList();}
 @Override @Transactional(readOnly=true) @PermissionNode(key="choose_quota_resources",description="Choose typed finite quota resources for Offer bonuses")public List<CommercialOfferViews.QuotaResourceChoice> chooseQuotaResources(String query){String term=query==null?"":query.trim().toLowerCase(Locale.ROOT);return featureRepository.findAll().stream().filter(feature->feature.isPublicVisible()&&feature.isNewGrantsEnabled()).flatMap(feature->feature.getQuotaSchema().stream().map(slot->new CommercialOfferViews.QuotaResourceChoice(feature.getCode(),feature.getCode(),slot.resource(),slot.unit()))).filter(item->term.isBlank()||item.featureCode().toLowerCase(Locale.ROOT).contains(term)||item.resource().toLowerCase(Locale.ROOT).contains(term)).limit(100).toList();}
 @Override @Transactional(readOnly=true) @PermissionNode(key="choose_owners",description="Choose active Offer owners")public Page<CommercialOfferViews.Owner> chooseOwners(String query,Pageable p){return admins.searchPageWithUser(query==null||query.isBlank()?null:query.trim(),true,bounded(p)).map(this::ownerChoice);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="resolve_owner_choices",description="Resolve selected Offer owners")public List<CommercialOfferViews.Owner> resolveOwnerChoices(Collection<UUID> ids){if(ids==null||ids.isEmpty()||ids.size()>100)throw new InvalidRequestException("Between 1 and 100 owner ids are required.");return admins.findAllWithUserByIdIn(ids).stream().map(this::ownerChoice).toList();}
 @Override @Transactional(readOnly=true) @PermissionNode(key="choose_campaigns",description="Choose exact Campaign revisions for Offers")public Page<CommercialOfferViews.Choice> chooseCampaigns(String query,Pageable p){String term=query==null||query.isBlank()?null:query.trim().toLowerCase(Locale.ROOT);Specification<CommercialCampaign> spec=(root,q,cb)->{var predicates=new ArrayList<jakarta.persistence.criteria.Predicate>();predicates.add(cb.notEqual(root.get("status"),CommercialCampaignStatus.ARCHIVED));if(term!=null){String pattern="%"+term.replace("%","\\%").replace("_","\\_")+"%";predicates.add(cb.or(cb.like(cb.lower(root.get("name")),pattern,'\\'),cb.like(cb.lower(root.get("code")),pattern,'\\')));}return cb.and(predicates.toArray(jakarta.persistence.criteria.Predicate[]::new));};return campaigns.findAll(spec,bounded(p)).map(this::campaignChoice);}
 @Override @Transactional(readOnly=true) @PermissionNode(key="resolve_campaign_choices",description="Resolve selected exact Campaign revisions")public List<CommercialOfferViews.Choice> resolveCampaignChoices(Collection<UUID> ids){if(ids==null||ids.isEmpty()||ids.size()>100)throw new InvalidRequestException("Between 1 and 100 Campaign ids are required.");return campaigns.findAllById(ids).stream().map(this::campaignChoice).toList();}
 @Override @Transactional(readOnly=true) @PermissionNode(key="preview_for_account",description="Preview an Offer for one Account")public CommercialOfferViews.EligibilityPreview previewForAccount(UUID offerId,UUID accountId){return commercialOfferService.preview(accountId,authorizer.currentActorUserId(),offerId,null,true);}
 @Override @Transactional @PermissionNode(key="apply_for_account",description="Apply a reviewed Offer for one Account")public CommercialOfferViews.Acceptance applyForAccount(UUID offerId,UUID accountId,String key,CommercialOfferRequests.Accept request){return commercialOfferService.accept(accountId,authorizer.currentActorUserId(),offerId,key,request,true);}

 private List<String> publicationBlockers(CommercialOffer o){List<String>b=new ArrayList<>();if(o.getStatus()!=CommercialOfferStatus.DRAFT)b.add("NOT_DRAFT");if(o.getDiscovery()==CommercialOfferDiscovery.CODE_ONLY&&o.getCustomerCodeHash()==null)b.add("CODE_REQUIRED");if(!Set.of(CommercialCampaignStatus.SCHEDULED,CommercialCampaignStatus.ACTIVE,CommercialCampaignStatus.PAUSED).contains(o.getCampaign().getStatus()))b.add("CAMPAIGN_NOT_LIVE");if(o.getStartsAt().isBefore(o.getCampaign().getStartsAt())||o.getEndsAt().isAfter(o.getCampaign().getEndsAt()))b.add("WINDOW_OUTSIDE_CAMPAIGN");try{validateSelection(o);}catch(RuntimeException e){b.add("INVALID_SELECTION");}return List.copyOf(b);}
 private void validateSelection(CommercialOffer o){var s=o.getSelection();var planPrice=prices.findOwned(ProductPriceOwnerType.PLAN,s.planId(),s.planPriceId()).orElseThrow(()->new InvalidRequestException("Exact Plan price does not belong to the selected Plan."));validatePrice(planPrice,o);requireDirectOnlyAudience(o,planPrice.getPlan().getSalesVisibility());String currency=planPrice.getCurrencyCode();var cycle=planPrice.getBillingCycle();Set<UUID>addOnIds=new HashSet<>();for(var item:s.addOns()){if(!addOnIds.add(item.addOnId()))throw new InvalidRequestException("An Add-on can be selected only once.");var p=prices.findOwned(ProductPriceOwnerType.ADD_ON,item.addOnId(),item.priceId()).orElseThrow(()->new InvalidRequestException("Exact Add-on price is invalid."));sameTerms(p,currency,cycle,o);requireDirectOnlyAudience(o,p.getAddOn().getSalesVisibility());}Set<UUID>packageIds=new HashSet<>();for(var q:s.quotaPackages()){if(!packageIds.add(q.quotaPackageId()))throw new InvalidRequestException("A capacity package can be selected only once.");var p=prices.findOwned(ProductPriceOwnerType.QUOTA_PACKAGE,q.quotaPackageId(),q.priceId()).orElseThrow(()->new InvalidRequestException("Exact capacity-package price is invalid."));sameTerms(p,currency,cycle,o);requireDirectOnlyAudience(o,p.getQuotaPackage().getSalesVisibility());}validateQuotaBonuses(o,addOnIds);Set<String> addOnCodes=addOnIds.isEmpty()?Set.of():addOns.findAllDetailedByIdIn(addOnIds).stream().map(AddOn::getCode).collect(java.util.stream.Collectors.toSet());List<QuotaPackageSelection> selectedPackages=s.quotaPackages().stream().map(item->new QuotaPackageSelection(quotaPackages.findById(item.quotaPackageId()).orElseThrow(()->new InvalidRequestException("Capacity package is missing.")).getCode(),item.quantity())).toList();CommercialCatalogResolver.requireSelectable(catalogResolver.resolveSelection(planPrice.getPlan(),planPrice,addOnCodes,selectedPackages,CommercialCatalogResolver.Audience.AUTHORIZED_OPERATOR),CommercialCatalogResolver.Audience.AUTHORIZED_OPERATOR);}
 private void requireDirectOnlyAudience(CommercialOffer offer,ProductSalesVisibility visibility){if(visibility==ProductSalesVisibility.DIRECT_ONLY&&(offer.getCampaign().getAudienceMode()==CommercialCampaignAudienceMode.PUBLIC||offer.getDiscovery()==CommercialOfferDiscovery.CODE_ONLY))throw new InvalidRequestException("DIRECT_ONLY products require a targeted frozen Campaign and cannot rely only on a customer code.");}
 private void validateQuotaBonuses(CommercialOffer offer,Set<UUID> addOnIds){Map<String,List<com.hiveapp.shared.quota.QuotaLimitEntry>> quotas=new HashMap<>();planFeatures.findAllByPlanId(offer.getSelection().planId()).stream().filter(item->item.getMode()==PlanFeatureMode.INCLUDED).forEach(item->quotas.put(item.getFeature().getCode(),item.getQuotaConfigs()));if(!addOnIds.isEmpty())for(var addOn:addOns.findAllDetailedByIdIn(addOnIds))for(var feature:addOn.getFeatures())quotas.put(feature.getFeature().getCode(),feature.getQuotaConfigs());for(var bonus:offer.getEffects().finiteQuotaBonuses()){boolean finite=quotas.getOrDefault(bonus.featureCode(),List.of()).stream().anyMatch(item->item.resource().equals(bonus.resource())&&item.mode()==com.hiveapp.shared.quota.QuotaLimitMode.FINITE);if(!finite)throw new InvalidRequestException("Offer quota bonus must target a finite quota in the exact selection: "+bonus.featureCode()+"."+bonus.resource());}}
 private void validatePrice(ProductPrice p,CommercialOffer o){if(p.getStatus()!=ProductPriceStatus.ACTIVE||p.getEffectiveFrom().isAfter(o.getStartsAt())||p.getEffectiveUntil()!=null&&!p.getEffectiveUntil().isAfter(o.getEndsAt()))throw new InvalidRequestException("Exact price must remain active for the Offer window.");}
 private void sameTerms(ProductPrice p,String currency,BillingCycle cycle,CommercialOffer o){validatePrice(p,o);if(!p.getCurrencyCode().equals(currency)||p.getBillingCycle()!=cycle)throw new InvalidRequestException("Offer exact prices must share currency and billing cycle.");}
 private void reserveCode(CommercialOffer o){if(o.getCustomerCodeHash()==null)return;var existing=codes.findByNormalizedCodeHash(o.getCustomerCodeHash());if(existing.isPresent()&&!existing.get().getLineageId().equals(o.getLineageId()))throw new OfferCodeConflictException();if(existing.isEmpty())try{codes.saveAndFlush(CommercialOfferCodeReservation.reserveHash(o.getCustomerCodeHash(),o.getLineageId()));}catch(DataIntegrityViolationException e){throw new OfferCodeConflictException();}}
 private CommercialOffer require(UUID id){return offers.findDetailById(id).orElseThrow(()->new ResourceNotFoundException("CommercialOffer","id",id));} private CommercialOffer lock(UUID id){return offers.findForUpdate(id).orElseThrow(()->new ResourceNotFoundException("CommercialOffer","id",id));}
 private CommercialCampaign requireCampaign(UUID id){return campaigns.findDetailById(id).orElseThrow(()->new ResourceNotFoundException("CommercialCampaign","id",id));}
 private AdminUser currentOwner(){return admins.findWithUserById(authorizer.currentActorAdminUserId()).orElseThrow(()->new ResourceNotFoundException("AdminUser","id",authorizer.currentActorAdminUserId()));}
 private void version(CommercialOffer o,long v){if(o.getVersion()!=v)throw new StaleResourceVersionException("Offer changed since it was read.");}
 private String nextCode(String n){return CommercialCodeGenerator.generate(n,"OFFER",lineages::existsByBusinessCode);}
 private String fingerprint(CommercialOffer o,List<String>b){return sha(o.getId()+"|"+o.getVersion()+"|"+o.getCampaign().getId()+"|"+o.getSelection()+"|"+o.getEffects()+"|"+b);}
 static String sha(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private CommercialOfferViews.Summary summary(CommercialOffer o){var a=actions(o);return new CommercialOfferViews.Summary(o.getId(),o.getBusinessCode(),o.getName(),o.getStatus(),o.getDiscovery(),o.getAcceptance(),o.getStartsAt(),o.getEndsAt(),o.getRevisionNumber(),o.getVersion(),a.available(),a.blocked());}
 private CommercialOfferViews.Detail detail(CommercialOffer o){var a=actions(o);return new CommercialOfferViews.Detail(o.getId(),o.getBusinessCode(),o.getName(),o.getDescription(),o.getStatus(),o.getDiscovery(),o.getAcceptance(),o.getCustomerCodeHash()!=null,o.getCampaign().getId(),o.getCampaign().getCode(),o.getStartsAt(),o.getEndsAt(),o.getLineageId(),o.getRevisionNumber(),o.getGlobalLimit(),o.getPerAccountLimit(),o.getSelection(),o.getEffects(),o.getPublishedAt(),o.getRetiredAt(),o.getArchivedAt(),o.getVersion(),a.available(),a.blocked());}
 private ActionState actions(CommercialOffer o){Set<String>all=Set.of("UPDATE","DUPLICATE","REVISE","PUBLISH","RETIRE","RESTORE","ARCHIVE","DELETE","REASSIGN_OWNER");Set<String>available=switch(o.getStatus()){case DRAFT->Set.of("UPDATE","DUPLICATE","PUBLISH","DELETE","REASSIGN_OWNER");case PUBLISHED->Set.of("DUPLICATE","REVISE","RETIRE","REASSIGN_OWNER");case RETIRED->Set.of("DUPLICATE","REVISE","RESTORE","ARCHIVE","REASSIGN_OWNER");case ARCHIVED->Set.of("DUPLICATE");};Map<String,String>blocked=new LinkedHashMap<>();for(String action:all)if(!available.contains(action))blocked.put(action,"Unavailable while Offer is "+o.getStatus()+".");return new ActionState(available,Map.copyOf(blocked));}
 private record ActionState(Set<String>available,Map<String,String>blocked){}
 private CommercialOfferViews.PricedChoice pricedChoice(ProductPrice price){return switch(price.getOwnerType()){case PLAN->new CommercialOfferViews.PricedChoice(price.getPlan().getId(),price.getPlan().getCode(),price.getPlan().getName(),price.getId(),price.getAmount(),price.getCurrencyCode(),price.getBillingCycle(),price.getPlan().getStatus().name(),price.getStatus().name());case ADD_ON->new CommercialOfferViews.PricedChoice(price.getAddOn().getId(),price.getAddOn().getCode(),price.getAddOn().getName(),price.getId(),price.getAmount(),price.getCurrencyCode(),price.getBillingCycle(),price.getAddOn().getStatus().name(),price.getStatus().name());case QUOTA_PACKAGE->new CommercialOfferViews.PricedChoice(price.getQuotaPackage().getId(),price.getQuotaPackage().getCode(),price.getQuotaPackage().getName(),price.getId(),price.getAmount(),price.getCurrencyCode(),price.getBillingCycle(),price.getQuotaPackage().getStatus().name(),price.getStatus().name());};}
 private CommercialOfferViews.Owner ownerChoice(AdminUser owner){return new CommercialOfferViews.Owner(owner.getId(),owner.getUser().getEmail(),owner.isActive());}
 private CommercialOfferViews.Choice campaignChoice(CommercialCampaign campaign){return new CommercialOfferViews.Choice(campaign.getId(),campaign.getCode(),campaign.getName()+" · r"+campaign.getRevisionNumber(),campaign.getStatus().name());}
 private CommercialOfferViews.Redemption redemption(CommercialOfferRedemption r){return new CommercialOfferViews.Redemption(r.getId(),r.getOffer().getId(),r.getOffer().getName(),r.getStatus(),r.getSurface(),r.getSubscriptionOperationId(),r.getReservedAt(),r.getAppliedAt(),r.getReleasedAt(),r.getTerminalReason());}
 private Pageable bounded(Pageable p){if(p==null||p.getPageNumber()<0||p.getPageSize()<1||p.getPageSize()>100)throw new InvalidRequestException("Page must be non-negative and size between 1 and 100.");return p;}
 private void translate(Runnable r){try{r.run();}catch(IllegalArgumentException e){throw new InvalidRequestException(e.getMessage());}catch(IllegalStateException e){throw new InvalidStateException(e.getMessage());}}
}
