package com.hiveapp.platform.client.plan.service.impl;

import com.hiveapp.platform.client.account.domain.repository.AccountRepository;
import com.hiveapp.platform.client.plan.domain.constant.*;
import com.hiveapp.platform.client.plan.domain.entity.*;
import com.hiveapp.platform.client.plan.domain.repository.*;
import com.hiveapp.platform.client.plan.dto.*;
import com.hiveapp.platform.client.plan.service.*;
import com.hiveapp.platform.registry.service.RegistryCatalogVersionService;
import com.hiveapp.shared.exception.*;
import com.hiveapp.shared.money.Money;
import dev.karroumi.permissionizer.PermissionNode;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.*;
import java.math.*;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
public class CommercialOfferServiceImpl implements CommercialOfferService{
 private static final List<CommercialOfferRedemptionStatus> USED=List.of(CommercialOfferRedemptionStatus.RESERVED,CommercialOfferRedemptionStatus.APPLIED);
 private final CommercialOfferRepository offers;private final CommercialOfferRedemptionRepository redemptions;private final CommercialOfferCapacityRepository capacities;
 private final CommercialCampaignAudienceSnapshotRepository audiences;private final AccountRepository accounts;private final SubscriptionRepository subscriptions;
 private final PlanRepository plans;private final AddOnRepository addOns;private final QuotaPackageRepository packages;private final ProductPriceRepository prices;
 private final SubscriptionService subscriptionsService;private final CommercialCatalogVersionService catalogVersions;private final RegistryCatalogVersionService registryVersions;private final CommercialPreviewTokenService previewTokens;private final Clock clock;
 private final CommercialOfferCodeHasher codeHasher;

 @Override @Transactional(readOnly=true) public Page<CommercialOfferViews.ClientOffer> catalogue(UUID accountId,Pageable p){return offers.findEligibleClientCatalogue(accountId,clock.instant(),p).map(this::client);}
 @Override @Transactional(readOnly=true) public CommercialOfferViews.ClientOffer detail(UUID accountId,UUID id){var o=requireAvailable(id,accountId,false,false);if(o.getDiscovery()!=CommercialOfferDiscovery.CATALOG)throw new OfferNotAvailableException();return client(o);}
 @Override @Transactional(readOnly=true) public CommercialOfferViews.CodeResolution resolveCode(UUID accountId,UUID actor,CommercialOfferRequests.ResolveCode r){try{String hash=codeHasher.hash(r.code());var found=offers.findPublishedByReservedCodeHash(hash,PageRequest.of(0,2));if(found.size()!=1)throw new OfferNotAvailableException();var o=found.getFirst();if(!eligible(o,accountId,false,true))throw new OfferNotAvailableException();long catalog=catalogVersions.currentRevision();String registry=registryVersions.currentVersion();String fp=discoveryFingerprint(o,accountId);var evidence=previewTokens.issue(CommercialPreviewKind.COMMERCIAL_OFFER_REDEMPTION,o.getId(),o.getVersion(),actor,catalog,registry,fp,clock.instant());return new CommercialOfferViews.CodeResolution(client(o),evidence.expiresAt(),evidence.token());}catch(OfferNotAvailableException e){throw e;}catch(RuntimeException e){throw new OfferNotAvailableException();}}
 @Override @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ) public CommercialOfferViews.EligibilityPreview preview(UUID accountId,UUID actor,UUID id,String discoveryToken,boolean operator){var o=requireAvailable(id,accountId,operator,true);if(!operator&&o.getDiscovery()==CommercialOfferDiscovery.CODE_ONLY){previewTokens.requireValid(discoveryToken,CommercialPreviewKind.COMMERCIAL_OFFER_REDEMPTION,o.getId(),o.getVersion(),actor,catalogVersions.currentRevision(),registryVersions.currentVersion(),discoveryFingerprint(o,accountId),OfferNotAvailableException::new);}return buildPreview(o,accountId,actor,operator);}
 @Override @Transactional(isolation=Isolation.SERIALIZABLE) public CommercialOfferViews.Acceptance accept(UUID accountId,UUID actor,UUID id,String key,CommercialOfferRequests.Accept r,boolean operator){if(key==null||key.isBlank()||key.length()>200)throw new InvalidRequestException("Idempotency-Key is required and must not exceed 200 characters.");accounts.findByIdForSubscriptionUpdate(accountId).orElseThrow(OfferNotAvailableException::new);String keyHash=CommercialOfferAdminServiceImpl.sha(accountId+"|"+key);var replay=redemptions.findByAccount_IdAndIdempotencyKeyHash(accountId,keyHash);if(replay.isPresent()){var old=replay.get();if(!old.getOffer().getId().equals(id))throw new InvalidStateException("Idempotency key was already used for different Offer input.");return new CommercialOfferViews.Acceptance(old.getId(),old.getSubscriptionOperationId(),old.getStatus(),true,accepted(old));}var o=requireAvailable(id,accountId,operator,true);var currentPreview=buildPreview(o,accountId,actor,operator);String fp=fingerprint(o,accountId,currentPreview);long catalog=catalogVersions.currentRevision();String registry=registryVersions.currentVersion();previewTokens.requireValid(r.previewToken(),CommercialPreviewKind.COMMERCIAL_OFFER_REDEMPTION,o.getId(),o.getVersion(),actor,catalog,registry,fp,StaleOfferPreviewException::new);
  var capacity=capacities.lockByLineage(o.getLineageId()).orElseThrow(OfferRedemptionBlockedException::new);long used=redemptions.countByOfferLineageIdAndAccount_IdAndStatusIn(o.getLineageId(),accountId,USED);capacity.reserve(o.getGlobalLimit()==null?-1:o.getGlobalLimit(),used,o.getPerAccountLimit()==null?-1:o.getPerAccountLimit());
  var account=accounts.findById(accountId).orElseThrow(OfferNotAvailableException::new);var redemption=CommercialOfferRedemption.reserve(account,o,operator?CommercialOfferSurface.OPERATOR:CommercialOfferSurface.CLIENT,actor,keyHash,fp,Map.of("catalogueSubtotal",currentPreview.catalogueSubtotal().toPlainString(),"policyPrice",currentPreview.policyPrice().toPlainString(),"offerPrice",currentPreview.offerPrice().toPlainString(),"finalPrice",currentPreview.finalPrice().toPlainString(),"currency",currentPreview.currencyCode(),"winner",currentPreview.discountWinner(),"winnerReason",currentPreview.winnerReason()),clock.instant());redemption=redemptions.saveAndFlush(redemption);
  try{SubscriptionChangeRequest selection=changeRequest(o);var changePreview=operator?subscriptionsService.previewChangeAsOperator(accountId,actor,selection):subscriptionsService.previewChange(accountId,actor,selection);var applied=subscriptionsService.applyOfferChange(accountId,actor,new SubscriptionChangeApplyRequest(selection,changePreview.previewToken()),r.reason()==null?"Accepted commercial Offer":r.reason(),operator,redemption.getId(),offerEvaluation(o,currentPreview));redemption.linkOperation(applied.operation().id());if(applied.operation().status()==SubscriptionChangeStatus.APPLIED){redemption.apply(clock.instant());capacity.apply();}return new CommercialOfferViews.Acceptance(redemption.getId(),redemption.getSubscriptionOperationId(),redemption.getStatus(),false,accepted(currentPreview));}catch(RuntimeException e){redemption.fail("SUBSCRIPTION_APPLICATION_FAILED",clock.instant());capacity.release();throw e;}}
 @Override @Transactional(readOnly=true) public Page<CommercialOfferViews.ClientRedemption> history(UUID accountId,Pageable p){return redemptions.findAllByAccount_Id(accountId,p).map(this::clientRedemption);}
 @Override @Transactional(readOnly=true) public CommercialOfferViews.ClientRedemption redemption(UUID accountId,UUID id){return clientRedemption(redemptions.findByIdAndAccount_Id(id,accountId).orElseThrow(OfferNotAvailableException::new));}

 private CommercialOfferViews.EligibilityPreview buildPreview(CommercialOffer o,UUID accountId,UUID actor,boolean operator){SubscriptionChangeRequest request=changeRequest(o);var p=operator?subscriptionsService.previewChangeAsOperator(accountId,actor,request):subscriptionsService.previewChange(accountId,actor,request);var policy=p.commercialPolicyEvaluation();BigDecimal catalogue=policy==null? p.previewPrice():policy.catalogueRecurringPrice();BigDecimal fixedBase=policy==null?catalogue:policy.fixedRecurringPrice();BigDecimal policyPrice=policy==null?p.previewPrice():policy.finalRecurringPrice();BigDecimal freeReduction=freeProductReduction(o);BigDecimal offerBase=fixedBase.subtract(freeReduction).max(BigDecimal.ZERO);BigDecimal offerPrice=discount(offerBase,o.getEffects());int comparison=offerPrice.compareTo(policyPrice);String winner=comparison<0?"OFFER":"POLICY";String winnerReason=winnerReason(winner);BigDecimal finalPrice=comparison<0?offerPrice:policyPrice;long catalog=catalogVersions.currentRevision();String registry=registryVersions.currentVersion();String fp=pricingFingerprint(o,accountId,p.subscriptionId(),p.expectedSubscriptionVersion(),catalogue,policyPrice,offerPrice,finalPrice,winner);var evidence=previewTokens.issue(CommercialPreviewKind.COMMERCIAL_OFFER_REDEMPTION,o.getId(),o.getVersion(),actor,catalog,registry,fp,clock.instant());return new CommercialOfferViews.EligibilityPreview(o.getId(),p.subscriptionId(),p.expectedSubscriptionVersion(),catalogue,policyPrice,offerPrice,finalPrice,p.currencyCode(),fixedBase,freeReduction,winner,winnerReason,evidence.evaluatedAt(),evidence.expiresAt(),evidence.token());}
 private BigDecimal freeProductReduction(CommercialOffer offer){BigDecimal total=BigDecimal.ZERO;for(var item:offer.getSelection().addOns())if(item.pricingMode()==CommercialOfferSelection.PricingMode.FREE)total=total.add(prices.findById(item.priceId()).orElseThrow(OfferNotAvailableException::new).getAmount());for(var item:offer.getSelection().quotaPackages())if(item.pricingMode()==CommercialOfferSelection.PricingMode.FREE)total=total.add(prices.findById(item.priceId()).orElseThrow(OfferNotAvailableException::new).getAmount().multiply(BigDecimal.valueOf(item.quantity())));return total;}
 private SubscriptionOfferEvaluation offerEvaluation(CommercialOffer offer,CommercialOfferViews.EligibilityPreview preview){return new SubscriptionOfferEvaluation(offer.getCampaign().getId(),offer.getLineageId(),offer.getId(),offer.getRevisionNumber(),preview.catalogueSubtotal(),preview.policyPrice(),preview.offerPrice(),preview.finalPrice(),preview.currencyCode(),preview.discountWinner(),preview.winnerReason(),offer.getEffects().finiteQuotaBonuses());}
 private String winnerReason(String winner){return "OFFER".equals(winner)?"Offer produces the lower payable recurring price.":"Commercial Policy produces an equal or lower payable recurring price; exact ties prefer Policy.";}
 private BigDecimal discount(BigDecimal base,CommercialOfferEffectSnapshot e){return switch(e.discountType()){case NONE->base;case FIXED->base.subtract(e.discountAmount()).max(BigDecimal.ZERO);case PERCENTAGE_WITH_CAP->{BigDecimal reduction=base.multiply(e.percentage()).divide(new BigDecimal("100"),4,RoundingMode.HALF_UP).min(e.percentageCap());yield base.subtract(reduction).max(BigDecimal.ZERO);}};}
 private SubscriptionChangeRequest changeRequest(CommercialOffer o){var s=o.getSelection();var plan=plans.findById(s.planId()).orElseThrow(OfferNotAvailableException::new);Set<String> addonCodes=new LinkedHashSet<>();Map<String,UUID> addOnPrices=new LinkedHashMap<>();for(var item:s.addOns()){String code=addOns.findById(item.addOnId()).orElseThrow(OfferNotAvailableException::new).getCode();addonCodes.add(code);addOnPrices.put(code,item.priceId());}Map<String,UUID> packagePrices=new LinkedHashMap<>();List<QuotaPackageSelection> qs=s.quotaPackages().stream().map(x->{String code=packages.findById(x.quotaPackageId()).orElseThrow(OfferNotAvailableException::new).getCode();packagePrices.put(code,x.priceId());return new QuotaPackageSelection(code,x.quantity());}).toList();return new SubscriptionChangeRequest(plan.getCode(),addonCodes,qs,s.timing(),new ProductPriceSelectionRequest(s.planPriceId(),null,null),addOnPrices,packagePrices);}
 private CommercialOffer requireAvailable(UUID id,UUID accountId,boolean operator,boolean discovered){var o=offers.findDetailById(id).orElseThrow(OfferNotAvailableException::new);if(!eligible(o,accountId,operator,discovered))throw new OfferNotAvailableException();return o;}
 private boolean eligible(CommercialOffer o,UUID accountId,boolean operator,boolean discovered){Instant now=clock.instant();if(o.getStatus()!=CommercialOfferStatus.PUBLISHED||now.isBefore(o.getStartsAt())||!now.isBefore(o.getEndsAt())||o.getCampaign().getStatus()!=CommercialCampaignStatus.ACTIVE)return false;if(!operator&&o.getAcceptance()==CommercialOfferAcceptance.OPERATOR_ONLY)return false;if(!discovered&&o.getDiscovery()!=CommercialOfferDiscovery.CATALOG)return false;var snapshot=audiences.findWithAccountsByCampaignId(o.getCampaign().getId()).orElse(null);return snapshot!=null&&(snapshot.getAudienceMode()==CommercialCampaignAudienceMode.PUBLIC||snapshot.getAccountIds().contains(accountId))&&subscriptions.findTopByAccountIdAndStatusInOrderByCreatedAtDesc(accountId,List.of(SubscriptionStatus.ACTIVE,SubscriptionStatus.TRIALING)).isPresent();}
 private CommercialOfferViews.ClientOffer client(CommercialOffer o){var plan=plans.findById(o.getSelection().planId()).orElseThrow(OfferNotAvailableException::new);return new CommercialOfferViews.ClientOffer(o.getId(),o.getName(),o.getDescription(),o.getEndsAt(),plan.getCode(),o.getEffects().discountType(),o.getEffects().discountAmount(),o.getEffects().percentage(),o.getEffects().percentageCap(),o.getSelection(),o.getEffects());}
 private CommercialOfferViews.ClientOffer unavailable(){throw new OfferNotAvailableException();}
 private String fingerprint(CommercialOffer o,UUID a,CommercialOfferViews.EligibilityPreview p){return pricingFingerprint(o,a,p.subscriptionId(),p.expectedSubscriptionVersion(),p.catalogueSubtotal(),p.policyPrice(),p.offerPrice(),p.finalPrice(),p.discountWinner());}
 private String pricingFingerprint(CommercialOffer o,UUID a,UUID s,long v,BigDecimal catalogue,BigDecimal policy,BigDecimal offer,BigDecimal result,String winner){return CommercialOfferAdminServiceImpl.sha(fingerprint(o,a,s,v,catalogue,result)+"|"+policy.toPlainString()+"|"+offer.toPlainString()+"|"+winner);}
 private String discoveryFingerprint(CommercialOffer o,UUID accountId){return CommercialOfferAdminServiceImpl.sha("DISCOVERY|"+o.getId()+"|"+o.getVersion()+"|"+accountId);}
 private CommercialOfferViews.AcceptedTerms accepted(CommercialOfferRedemption r){var e=r.getCommercialEvaluation();return new CommercialOfferViews.AcceptedTerms(decimal(e,"catalogueSubtotal"),decimal(e,"policyPrice"),decimal(e,"offerPrice"),decimal(e,"finalPrice"),String.valueOf(e.get("currency")),String.valueOf(e.get("winner")),String.valueOf(e.get("winnerReason")));}
 private CommercialOfferViews.AcceptedTerms accepted(CommercialOfferViews.EligibilityPreview p){return new CommercialOfferViews.AcceptedTerms(p.catalogueSubtotal(),p.policyPrice(),p.offerPrice(),p.finalPrice(),p.currencyCode(),p.discountWinner(),p.winnerReason());}
 private BigDecimal decimal(Map<String,Object> values,String key){return new BigDecimal(String.valueOf(values.get(key)));}
 private String fingerprint(CommercialOffer o,UUID a,UUID s,long v,BigDecimal b,BigDecimal f){return CommercialOfferAdminServiceImpl.sha(o.getId()+"|"+o.getVersion()+"|"+a+"|"+s+"|"+v+"|"+b.toPlainString()+"|"+f.toPlainString()+"|"+o.getSelection()+"|"+o.getEffects());}
 private CommercialOfferViews.Redemption redemption(CommercialOfferRedemption r){return new CommercialOfferViews.Redemption(r.getId(),r.getOffer().getId(),r.getOffer().getName(),r.getStatus(),r.getSurface(),r.getSubscriptionOperationId(),r.getReservedAt(),r.getAppliedAt(),r.getReleasedAt(),r.getTerminalReason());}
 private CommercialOfferViews.ClientRedemption clientRedemption(CommercialOfferRedemption r){return new CommercialOfferViews.ClientRedemption(r.getId(),r.getOffer().getId(),r.getOffer().getName(),r.getStatus(),r.getSubscriptionOperationId(),r.getReservedAt(),r.getAppliedAt(),r.getReleasedAt());}
}
