package com.hiveapp.platform.client.plan.domain.constant;

/** Stable semantic validation codes for Offer draft authoring. */
public enum CommercialOfferDefinitionIssueCode {
  CAMPAIGN_UNAVAILABLE,
  INVALID_WINDOW,
  WINDOW_OUTSIDE_CAMPAIGN,
  WINDOW_ENDED,
  CUSTOMER_CODE_REQUIRED,
  CUSTOMER_CODE_INVALID,
  CUSTOMER_CODE_UNAVAILABLE,
  PRICE_OWNER_MISMATCH,
  PRICE_INACTIVE_OR_WINDOW_UNCOVERED,
  CURRENCY_MISMATCH,
  BILLING_CYCLE_MISMATCH,
  DUPLICATE_PRODUCT_REVISION,
  DIRECT_ONLY_REQUIRES_TARGETED_CAMPAIGN,
  SELECTION_INCOMPATIBLE,
  QUOTA_BONUS_NOT_IN_SELECTION,
  INVALID_DISCOUNT,
  LINEAGE_TERMS_IMMUTABLE
}
