package com.hiveapp.platform.client.plan.domain.constant;

/** Stable activation blockers returned to operators before a signed apply. */
public enum CommercialPolicyBlocker {
    WRONG_LIFECYCLE_STATE,
    EFFECTIVE_WINDOW_EXPIRED,
    SEGMENT_RESOLUTION_UNAVAILABLE,
    TARGET_NOT_CONFIGURED,
    TARGET_ACCOUNT_MISSING,
    PLAN_REVISION_MISSING,
    EXPLICIT_ACCOUNT_SET_EMPTY,
    EXPLICIT_ACCOUNT_MISSING,
    AUDIENCE_EXCEEDS_ACTIVATION_LIMIT,
    LINEAGE_HAS_MULTIPLE_CURRENT_REVISIONS,
    NO_EFFECTS,
    INVALID_EFFECT,
    PRODUCT_REVISION_MISSING,
    PRODUCT_REVISION_NOT_ACTIVE,
    FEATURE_MISSING,
    FEATURE_NOT_COMMERCIALLY_GRANTABLE,
    QUOTA_RESOURCE_NOT_DECLARED,
    AUDIENCE_CURRENCY_MISMATCH
}
