package com.hiveapp.platform.client.plan.domain.constant;

public enum CommercialCampaignBlocker {
    NOT_DRAFT,
    NOT_SCHEDULED,
    NOT_ACTIVE,
    NOT_PAUSED,
    NOT_ENDED,
    ALREADY_ARCHIVED,
    INVALID_WINDOW,
    WINDOW_ENDED,
    EMPTY_AUDIENCE,
    AUDIENCE_TOO_LARGE,
    SEGMENT_NOT_ACTIVE,
    SEGMENT_ACTIVATION_STALE,
    NOT_LATEST_REVISION,
    DRAFT_SUCCESSOR_EXISTS,
    LIVE_LINEAGE_REVISION_EXISTS,
    HAS_SCHEDULE_HISTORY,
    HAS_DERIVED_CAMPAIGNS,
    HAS_OFFERS
}
