package com.hiveapp.platform.client.plan.domain.constant;

/** Stable, operator-facing reason codes. Client catalogues never expose rejected items or reasons. */
public enum ExtensionAvailabilityReason {
    PLAN_EXTENSIONS_CLOSED,
    NOT_ALLOW_LISTED,
    PLAN_EXPLICITLY_BLOCKED,
    OPTIONAL_TARGETING_EXCLUDED,
    PRODUCT_NOT_FOUND,
    PRODUCT_NOT_ACTIVE,
    DIRECT_ONLY,
    FEATURE_DEFINITION_MISSING,
    FEATURE_NOT_PLAN_ASSIGNABLE,
    FEATURE_NOT_CLIENT_FACING,
    FEATURE_NEW_SALES_DISABLED,
    FEATURE_RUNTIME_DISABLED,
    PLAN_FEATURE_NOT_OPTIONAL,
    DEPENDENCY_MISSING,
    DEPENDENCY_UNAVAILABLE,
    DEPENDENCY_CYCLE,
    DEPENDENCY_NOT_SELECTED,
    EXCLUDED_SELECTION,
    DUPLICATE_PAID_CAPABILITY,
    QUOTA_OWNER_MISSING,
    QUOTA_NOT_FINITE,
    PRICE_UNAVAILABLE,
    INVALID_QUANTITY
}
