export const ADMIN_PERMISSIONS = {
  FEATURE_CATALOG: 'platform.registry.feature_catalog',
  FEATURE_ACTIVE_UPDATE: 'platform.registry.update_active',
  PLAN_LIST: 'platform.plans.list',
  PLAN_CREATE: 'platform.plans.create',
  PLAN_TOGGLE_ACTIVE: 'platform.plans.toggle_active',
  PLAN_LIST_FEATURES: 'platform.plans.list_features',
  PLAN_ASSIGN_FEATURE: 'platform.plans.assign_feature',
  PLAN_UPDATE_FEATURE: 'platform.plans.update_feature',
  PLAN_REMOVE_FEATURE: 'platform.plans.remove_feature',
  ADMIN_USERS_READ: 'platform.admin_users.read',
  ADMIN_USERS_READ_DETAIL: 'platform.admin_users.read_detail',
  ADMIN_USERS_CREATE: 'platform.admin_users.create',
  ADMIN_USERS_TOGGLE: 'platform.admin_users.toggle_active',
  ADMIN_USERS_ASSIGN_ROLE: 'platform.admin_users.assign_role',
  ADMIN_USERS_REMOVE_ROLE: 'platform.admin_users.remove_role',
  ADMIN_ROLES_READ: 'platform.roles.read',
  ADMIN_ROLES_READ_DETAIL: 'platform.roles.read_detail',
  ADMIN_ROLES_CREATE: 'platform.roles.create',
  ADMIN_ROLES_UPDATE: 'platform.roles.update',
  ADMIN_ROLES_TOGGLE: 'platform.roles.toggle_active',
  ADMIN_ROLES_GRANT_PERMISSION: 'platform.roles.grant_permission',
  ADMIN_ROLES_REVOKE_PERMISSION: 'platform.roles.revoke_permission',
} as const
