<script setup lang="ts">
import {
  LayoutDashboard,
  Users,
  Layers3,
  Megaphone,
  Receipt,
  Workflow,
  Settings2,
  Search,
  ChevronDown,
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  Plus,
  X,
  Check,
  CheckCircle2,
  AlertCircle,
  Clock3,
  Bell,
  Menu,
  ChevronRight,
  ChevronLeft,
  SlidersHorizontal,
  RefreshCw,
  MoreHorizontal,
  Download,
  Command,
  ShieldCheck,
  Mail,
  CreditCard,
  Box,
  CalendarDays,
  Activity,
  Zap,
  Building2,
  Globe2,
  LogOut,
  ExternalLink,
  CircleHelp,
  CheckCheck,
  Play,
  Ban,
  Copy,
  Sparkles,
} from "lucide-vue-next";
const icons = {
  overview: LayoutDashboard,
  customers: Users,
  catalog: Layers3,
  commercial: Megaphone,
  billing: Receipt,
  operations: Workflow,
  settings: Settings2,
  search: Search,
  down: ChevronDown,
  arrow: ArrowUpRight,
  right: ArrowRight,
  back: ArrowLeft,
  plus: Plus,
  close: X,
  check: Check,
  success: CheckCircle2,
  alert: AlertCircle,
  clock: Clock3,
  bell: Bell,
  menu: Menu,
  next: ChevronRight,
  previous: ChevronLeft,
  filters: SlidersHorizontal,
  refresh: RefreshCw,
  more: MoreHorizontal,
  download: Download,
  command: Command,
  shield: ShieldCheck,
  mail: Mail,
  card: CreditCard,
  box: Box,
  calendar: CalendarDays,
  activity: Activity,
  zap: Zap,
  building: Building2,
  globe: Globe2,
  logout: LogOut,
  external: ExternalLink,
  help: CircleHelp,
  done: CheckCheck,
  play: Play,
  cancel: Ban,
  copy: Copy,
  sparkle: Sparkles,
};
defineProps<{ name: keyof typeof icons; size?: number }>();
</script>
<template>
  <component
    :is="icons[name]"
    :size="size || 18"
    :stroke-width="1.7"
    aria-hidden="true"
  />
</template>
