import { useTranslation } from "react-i18next";
import { i18n } from "@/app/i18n";

const copy = {
  status: ["État", "الحالة"],
  actions: ["Actions", "إجراءات"],
  availableShort: ["Disponibilité", "الإتاحة"],
  enabled: ["Autorisées", "مسموحة"],
  disabled: ["Désactivées", "معطلة"],
  inAppEmail: ["Application + email", "التطبيق والبريد"],
  inbox: ["Dans l’application", "داخل التطبيق"],
  visible: ["Visible", "ظاهر"],
  notVisible: ["Non visible", "غير ظاهر"],
  remove: ["Retirer", "إزالة"],
  draftOnly: [
    "Ce bouton enregistre un brouillon. Vous pourrez vérifier puis publier séparément.",
    "يحفظ هذا الزر مسودة. يمكنك مراجعتها ثم نشرها بشكل منفصل.",
  ],
  unsaved: ["Vos modifications ne seront pas conservées.", "لن تُحفظ تعديلاتك."],
  savePreferences: ["Enregistrer", "حفظ"],
  title: ["Communications", "التواصل"],
  refresh: ["Actualiser", "تحديث"],
  notifications: ["Notifications", "الإشعارات"],
  operatorInbox: ["Mes notifications", "إشعاراتي"],
  outbound: ["Communiquer aux clients", "التواصل مع العملاء"],
  personalSettings: ["Mes préférences", "تفضيلاتي"],
  requiredHint: [
    "Ces choix filtrent les informations facultatives du flux, sans bloquer leur lien direct. L’email est envoyé seulement si l’événement le prévoit. Les avertissements obligatoires et le consentement commercial restent séparés.",
    "تخفي هذه الخيارات المعلومات الاختيارية من القائمة دون منع رابطها المباشر. يرسل البريد فقط عندما يدعمه الحدث. التنبيهات الإلزامية والموافقة التجارية مستقلة.",
  ],
  topic: ["Domaine", "المجال"],
  GENERAL: ["Général", "عام"],
  ACCOUNT: ["Compte", "الحساب"],
  BILLING: ["Facturation", "الفوترة"],
  COLLABORATION: ["Collaborations", "التعاون"],
  COMMERCIAL: ["Offres et abonnement", "العروض والاشتراك"],
  OPERATIONS: ["Opérations", "العمليات"],
  TASKS: ["Tâches", "المهام"],
  ACTION: ["Actions à examiner", "إجراءات للمراجعة"],
  OFFER: ["Offres", "العروض"],
  actionHint: [
    "Ouvrez le dossier pour agir. Lire cette notification ne réalise pas l’action.",
    "افتح الملف لاتخاذ الإجراء. قراءة الإشعار لا تنفذ الإجراء.",
  ],
  offerHint: [
    "Présente une offre existante. L’éligibilité et les conditions sont vérifiées à la souscription.",
    "يعرض عرضا موجودا. يتم التحقق من الأهلية والشروط عند الاشتراك.",
  ],
  offer: ["Offre à présenter", "العرض المراد تقديمه"],
  offerChoose: ["Choisir une offre", "اختيار عرض"],
  offerRequired: [
    "Choisissez une offre publique active. Chaque compte sélectionné doit y être éligible.",
    "اختر عرضا عاما نشطا. يجب أن يكون كل حساب مختار مؤهلا له.",
  ],
  resolved: ["Traité à la source", "تمت المعالجة في المصدر"],
  UNAVAILABLE: ["Offre indisponible", "العرض غير متاح"],
  personal: ["Pour vous", "لك"],
  notifyMembers: ["Informer des membres", "إعلام الأعضاء"],
  internalHint: [
    "Information à sens unique pour les membres choisis de votre compte. Aucun accès supplémentaire n’est accordé.",
    "معلومة باتجاه واحد لأعضاء حسابك المختارين. لا تمنح أي صلاحيات إضافية.",
  ],
  memberSearch: ["Rechercher un membre", "البحث عن عضو"],
  member: ["Membre", "عضو"],
  selectedMembers: ["membres sélectionnés", "أعضاء مختارون"],
  reviewSend: ["Vérifier l’envoi", "مراجعة الإرسال"],
  send: ["Envoyer l’information", "إرسال المعلومة"],
  sentNotice: ["Information enregistrée pour les destinataires choisis.", "تم تسجيل المعلومة للمستلمين المختارين."],
  deliveryQueue: ["Suivi des notifications", "متابعة الإشعارات"],
  deliveryChannel: ["Canal de livraison", "قناة التسليم"],
  automaticEmail: ["Emails automatiques", "البريد التلقائي"],
  retryAutomaticEmailHint: [
    "Relance uniquement l’email. L’accès, les préférences et l’état du dossier seront revérifiés. Aucun événement métier n’est rejoué.",
    "يعيد محاولة البريد فقط. يعاد التحقق من الوصول والتفضيلات وحالة الملف، ولا يعاد تنفيذ العملية الأصلية.",
  ],
  event: ["Événement", "الحدث"],
  "account.information": ["Information interne", "معلومة داخلية"],
  "account.member_created": ["Membre ajouté", "عضو جديد"],
  "account.member_access_changed": ["Accès d’un membre modifié", "تغير وصول عضو"],
  "collaboration.requested": ["Demande de collaboration", "طلب تعاون"],
  "collaboration.changed": ["Collaboration mise à jour", "تحديث التعاون"],
  "billing.payment_received": ["Paiement enregistré", "تسجيل دفع"],
  "billing.payment_failed": ["Paiement non abouti", "فشل الدفع"],
  "operations.billing_attention": ["Paiement à vérifier", "دفع للمراجعة"],
  "commercial.offer_available": ["Offre proposée", "عرض مقترح"],
  attempts: ["Tentatives", "المحاولات"],
  nextAttempt: ["Prochaine tentative", "المحاولة التالية"],
  DELIVERED: ["Disponible dans l’application", "متاح في التطبيق"],
  retryEvent: ["Relancer", "إعادة المحاولة"],
  retryEventHint: [
    "Après correction de la cause, relancez cet événement. Les destinataires et le contenu ne changent pas.",
    "بعد تصحيح السبب أعد محاولة الحدث. لا يتغير المستلمون أو المحتوى.",
  ],
  billingAction: ["Consulter la facture", "عرض الفاتورة"],
  collaborationAction: ["Examiner la collaboration", "مراجعة التعاون"],
  offerAction: ["Voir l’offre et ses conditions", "عرض العرض وشروطه"],
  memberAction: ["Consulter les membres", "عرض الأعضاء"],
  subscriptionAction: ["Consulter mon abonnement", "عرض اشتراكي"],
  clients: ["Clients", "العملاء"],
  security: ["Emails de sécurité", "رسائل الأمان"],
  NOTICE: ["Informations", "إشعارات"],
  WARNING: ["Avertissements", "تحذيرات"],
  noticeHint: ["À lire et à conserver ou archiver.", "للقراءة والاحتفاظ أو الأرشفة."],
  warningHint: ["À examiner. « J’ai vu » ne résout pas le problème.", "للمراجعة. «اطلعت» لا يحل المشكلة."],
  SERVICE: ["Service", "الخدمة"],
  MARKETING: ["Commercial / marketing", "تجاري / تسويقي"],
  create: ["Composer", "إنشاء"],
  edit: ["Modifier le brouillon", "تعديل المسودة"],
  save: ["Enregistrer le brouillon", "حفظ المسودة"],
  DRAFT: ["Brouillon", "مسودة"],
  PUBLISHED: ["Publié", "منشور"],
  CANCELLED: ["Retiré", "مسحوب"],
  SCHEDULED: ["Prévu", "مجدول"],
  APPLIED: ["Appliqué", "مطبّق"],
  PENDING: ["En attente", "قيد الانتظار"],
  READY: ["Prêt", "جاهز"],
  AWAITING_PAYMENT: ["En attente de paiement", "بانتظار الدفع"],
  CONFLICT: ["Non appliqué", "غير مطبّق"],
  SENT: ["Email envoyé", "أُرسل البريد"],
  SUPPRESSED: ["Email non envoyé", "لم يُرسل البريد"],
  FAILED: ["Échec de l’envoi", "فشل الإرسال"],
  NOT_REQUESTED: ["Dans l’application", "داخل التطبيق"],
  SENDING: ["Envoi en cours", "جارٍ الإرسال"],
  WITHDRAWN: ["Retiré", "مسحوب"],
  back: ["Retour", "رجوع"],
  open: ["Ouvrir", "فتح"],
  empty: ["Aucune communication", "لا توجد مراسلات"],
  error: ["Impossible de terminer cette action.", "تعذر إكمال العملية."],
  all: ["Tout", "الكل"],
  unread: ["Non lus", "غير مقروء"],
  archives: ["Archives", "الأرشيف"],
  read: ["Marquer comme lu", "تحديد كمقروء"],
  seen: ["J’ai vu", "اطلعت"],
  acknowledged: ["Vu — le problème reste à traiter", "تم الاطلاع — ما زالت المشكلة تحتاج معالجة"],
  archive: ["Archiver", "أرشفة"],
  restore: ["Restaurer", "استعادة"],
  readState: ["Lu", "مقروء"],
  client: ["Client", "عميل"],
  team: ["Équipe HiveApp", "فريق HiveApp"],
  source: ["Voir les détails", "عرض التفاصيل"],
  PLAN_CONTENT: ["Évolution du forfait", "تطور الباقة"],
  REPRICING: ["Évolution du tarif", "تغير السعر"],
  sourceHint: [
    "Consultez les conditions et l’état actuel dans votre abonnement.",
    "راجع الشروط والحالة الحالية في اشتراكك.",
  ],
  prefs: ["Préférences commerciales", "تفضيلات التواصل التجاري"],
  prefHint: [
    "Les informations de service restent indépendantes de ces choix.",
    "إشعارات الخدمة مستقلة عن هذه الاختيارات.",
  ],
  marketingInApp: ["Recevoir les communications commerciales dans l’application", "تلقي التواصل التجاري داخل التطبيق"],
  marketingEmail: ["Recevoir les communications commerciales par email", "تلقي التواصل التجاري بالبريد"],
  saved: ["Enregistré", "تم الحفظ"],
  ownerOnly: ["Seul le propriétaire du compte peut modifier ces choix.", "مالك الحساب فقط يمكنه تعديل هذه الخيارات."],
  content: ["Contenu", "المحتوى"],
  recipients: ["Destinataires", "المستلمون"],
  review: ["Révision avant publication", "المراجعة قبل النشر"],
  type: ["Type", "النوع"],
  purpose: ["Objet", "الغرض"],
  subject: ["Titre", "العنوان"],
  body: ["Message", "المحتوى"],
  email: ["Envoyer aussi un email", "إرسال بريد أيضا"],
  emailHint: [
    "Le propriétaire vérifié reçoit l’email. L’envoi ne prouve ni lecture ni consentement.",
    "يُرسل البريد للمالك ذي العنوان المؤكد. الإرسال ليس إثبات قراءة أو موافقة.",
  ],
  now: ["Dès publication", "عند النشر"],
  available: ["Disponible à partir du (heure locale)", "متاح ابتداءً من (بالتوقيت المحلي)"],
  expiry: ["Expire le (facultatif)", "ينتهي في (اختياري)"],
  selected: ["comptes sélectionnés", "حسابات مختارة"],
  max: [
    "500 comptes maximum. L’audience est figée à la publication.",
    "500 حساب كحد أقصى. تُثبت قائمة المستلمين عند النشر.",
  ],
  search: ["Rechercher un compte", "البحث عن حساب"],
  select: ["Sélectionner", "اختيار"],
  next: ["Continuer", "متابعة"],
  publish: ["Publier / programmer", "نشر / جدولة"],
  cancel: ["Retirer", "سحب"],
  reason: ["Motif", "السبب"],
  confirm: ["Confirmer", "تأكيد"],
  dismiss: ["Fermer", "إغلاق"],
  immutable: [
    "Après publication, le contenu et les destinataires ne sont plus modifiables.",
    "بعد النشر لا يمكن تعديل المحتوى أو المستلمين.",
  ],
  marketingHint: [
    "Seuls les comptes ayant choisi de recevoir ce canal verront ou recevront cette communication.",
    "تظهر هذه الرسالة أو تُرسل فقط للحسابات التي اختارت تلقيها عبر القناة المعنية.",
  ],
  results: ["Suivi par compte", "المتابعة لكل حساب"],
  account: ["Compte", "الحساب"],
  delivery: ["Email", "البريد"],
  readers: ["Lecteurs", "القراء"],
  acknowledgements: ["Ont vu l’avertissement", "اطلعوا على التحذير"],
  retry: ["Réessayer l’email", "إعادة محاولة البريد"],
  scheduleHint: [
    "Une date future programme la visibilité et l’envoi. Une date vide signifie maintenant.",
    "موعد مستقبلي يجدول الظهور والإرسال. تركه فارغا يعني الآن.",
  ],
  cancelHint: [
    "Le retrait ne rappelle pas un email déjà en cours d’envoi et ne supprime pas l’historique.",
    "السحب لا يسترجع بريدا بدأ إرساله ولا يحذف السجل.",
  ],
  discard: ["Quitter sans enregistrer ?", "المغادرة دون حفظ؟"],
  leave: ["Quitter", "مغادرة"],
} as const;
export function useCommunicationCopy() {
  const { i18n } = useTranslation();
  const ar = i18n.language.startsWith("ar");
  return (key: string) => copy[key as keyof typeof copy]?.[ar ? 1 : 0] ?? key;
}
export function communicationDate(value: string | null, locale = i18n.language) {
  return value
    ? new Intl.DateTimeFormat(locale.startsWith("ar") ? "ar-MA" : "fr-MA", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date(value))
    : "—";
}
