import { useTranslation } from "react-i18next";
import { i18n } from "@/app/i18n";

const copy = {
  status: ["État", "الحالة"],
  actions: ["Actions", "إجراءات"],
  availableShort: ["Disponibilité", "الإتاحة"],
  enabled: ["Autorisées", "مسموحة"],
  disabled: ["Désactivées", "معطلة"],
  inAppEmail: ["Application + email", "التطبيق والبريد"],
  inbox: ["Dans l’application", "داخل التطبيق"],
  visible: ["Visible", "ظاهر"],
  notVisible: ["Non visible", "غير ظاهر"],
  privateThread: ["Conversation privée", "محادثة خاصة"],
  remove: ["Retirer", "إزالة"],
  draftOnly: [
    "Ce bouton enregistre un brouillon. Vous pourrez vérifier puis publier séparément.",
    "يحفظ هذا الزر مسودة. يمكنك مراجعتها ثم نشرها بشكل منفصل.",
  ],
  unsaved: ["Vos modifications ne seront pas conservées.", "لن تُحفظ تعديلاتك."],
  savePreferences: ["Enregistrer", "حفظ"],
  title: ["Communications", "التواصل"],
  clients: ["Clients", "العملاء"],
  security: ["Emails de sécurité", "رسائل الأمان"],
  NOTICE: ["Informations", "إشعارات"],
  WARNING: ["Avertissements", "تحذيرات"],
  MESSAGE: ["Messages", "رسائل"],
  noticeHint: ["À lire et à conserver ou archiver.", "للقراءة والاحتفاظ أو الأرشفة."],
  warningHint: ["À examiner. « J’ai vu » ne résout pas le problème.", "للمراجعة. «اطلعت» لا يحل المشكلة."],
  messageHint: ["Une conversation privée avec votre compte.", "محادثة خاصة بحسابك."],
  SERVICE: ["Service", "الخدمة"],
  MARKETING: ["Commercial / marketing", "تجاري / تسويقي"],
  create: ["Composer", "إنشاء"],
  edit: ["Modifier le brouillon", "تعديل المسودة"],
  save: ["Enregistrer le brouillon", "حفظ المسودة"],
  DRAFT: ["Brouillon", "مسودة"],
  PUBLISHED: ["Publié", "منشور"],
  CANCELLED: ["Retiré", "مسحوب"],
  SCHEDULED: ["Prévu", "مجدول"],
  APPLIED: ["Appliqué", "مطبّق"],
  PENDING: ["En attente", "قيد الانتظار"],
  READY: ["Prêt", "جاهز"],
  AWAITING_PAYMENT: ["En attente de paiement", "بانتظار الدفع"],
  CONFLICT: ["Non appliqué", "غير مطبّق"],
  SENT: ["Email envoyé", "أُرسل البريد"],
  SUPPRESSED: ["Email non envoyé", "لم يُرسل البريد"],
  FAILED: ["Échec de l’envoi", "فشل الإرسال"],
  NOT_REQUESTED: ["Dans l’application", "داخل التطبيق"],
  SENDING: ["Envoi en cours", "جارٍ الإرسال"],
  WITHDRAWN: ["Retiré", "مسحوب"],
  back: ["Retour", "رجوع"],
  open: ["Ouvrir", "فتح"],
  empty: ["Aucune communication", "لا توجد مراسلات"],
  error: ["Impossible de terminer cette action.", "تعذر إكمال العملية."],
  all: ["Tout", "الكل"],
  unread: ["Non lus", "غير مقروء"],
  archives: ["Archives", "الأرشيف"],
  read: ["Marquer comme lu", "تحديد كمقروء"],
  seen: ["J’ai vu", "اطلعت"],
  acknowledged: ["Vu — le problème reste à traiter", "تم الاطلاع — ما زالت المشكلة تحتاج معالجة"],
  archive: ["Archiver", "أرشفة"],
  restore: ["Restaurer", "استعادة"],
  readState: ["Lu", "مقروء"],
  reply: ["Répondre", "رد"],
  replyLabel: ["Votre réponse", "ردك"],
  sendReply: ["Envoyer la réponse", "إرسال الرد"],
  client: ["Client", "عميل"],
  team: ["Équipe HiveApp", "فريق HiveApp"],
  noReplies: ["Aucune réponse", "لا توجد ردود"],
  closed: ["Conversation fermée", "محادثة مغلقة"],
  closeThread: ["Fermer la conversation", "إغلاق المحادثة"],
  reopen: ["Rouvrir", "إعادة الفتح"],
  source: ["Voir les détails", "عرض التفاصيل"],
  PLAN_CONTENT: ["Évolution du forfait", "تطور الباقة"],
  REPRICING: ["Évolution du tarif", "تغير السعر"],
  sourceHint: [
    "Consultez les conditions et l’état actuel dans votre abonnement.",
    "راجع الشروط والحالة الحالية في اشتراكك.",
  ],
  prefs: ["Préférences commerciales", "تفضيلات التواصل التجاري"],
  prefHint: [
    "Les informations de service restent indépendantes de ces choix.",
    "إشعارات الخدمة مستقلة عن هذه الاختيارات.",
  ],
  marketingInApp: ["Recevoir les communications commerciales dans l’application", "تلقي التواصل التجاري داخل التطبيق"],
  marketingEmail: ["Recevoir les communications commerciales par email", "تلقي التواصل التجاري بالبريد"],
  saved: ["Enregistré", "تم الحفظ"],
  ownerOnly: ["Seul le propriétaire du compte peut modifier ces choix.", "مالك الحساب فقط يمكنه تعديل هذه الخيارات."],
  content: ["Contenu", "المحتوى"],
  recipients: ["Destinataires", "المستلمون"],
  review: ["Révision avant publication", "المراجعة قبل النشر"],
  type: ["Type", "النوع"],
  purpose: ["Objet", "الغرض"],
  subject: ["Titre", "العنوان"],
  body: ["Message", "المحتوى"],
  allowReplies: ["Permettre les réponses privées", "السماح بالردود الخاصة"],
  email: ["Envoyer aussi un email", "إرسال بريد أيضا"],
  emailHint: [
    "Le propriétaire vérifié reçoit l’email. L’envoi ne prouve ni lecture ni consentement.",
    "يُرسل البريد للمالك ذي العنوان المؤكد. الإرسال ليس إثبات قراءة أو موافقة.",
  ],
  now: ["Dès publication", "عند النشر"],
  available: ["Disponible à partir du (heure locale)", "متاح ابتداءً من (بالتوقيت المحلي)"],
  expiry: ["Expire le (facultatif)", "ينتهي في (اختياري)"],
  selected: ["comptes sélectionnés", "حسابات مختارة"],
  max: [
    "500 comptes maximum. L’audience est figée à la publication.",
    "500 حساب كحد أقصى. تُثبت قائمة المستلمين عند النشر.",
  ],
  search: ["Rechercher un compte", "البحث عن حساب"],
  select: ["Sélectionner", "اختيار"],
  next: ["Continuer", "متابعة"],
  publish: ["Publier / programmer", "نشر / جدولة"],
  cancel: ["Retirer", "سحب"],
  reason: ["Motif", "السبب"],
  confirm: ["Confirmer", "تأكيد"],
  dismiss: ["Fermer", "إغلاق"],
  immutable: [
    "Après publication, le contenu et les destinataires ne sont plus modifiables.",
    "بعد النشر لا يمكن تعديل المحتوى أو المستلمين.",
  ],
  marketingHint: [
    "Seuls les comptes ayant choisi de recevoir ce canal verront ou recevront cette communication.",
    "تظهر هذه الرسالة أو تُرسل فقط للحسابات التي اختارت تلقيها عبر القناة المعنية.",
  ],
  results: ["Suivi par compte", "المتابعة لكل حساب"],
  account: ["Compte", "الحساب"],
  delivery: ["Email", "البريد"],
  readers: ["Lecteurs", "القراء"],
  acknowledgements: ["Ont vu l’avertissement", "اطلعوا على التحذير"],
  replies: ["Réponses", "الردود"],
  retry: ["Réessayer l’email", "إعادة محاولة البريد"],
  scheduleHint: [
    "Une date future programme la visibilité et l’envoi. Une date vide signifie maintenant.",
    "موعد مستقبلي يجدول الظهور والإرسال. تركه فارغا يعني الآن.",
  ],
  cancelHint: [
    "Le retrait ne rappelle pas un email déjà en cours d’envoi et ne supprime pas l’historique.",
    "السحب لا يسترجع بريدا بدأ إرساله ولا يحذف السجل.",
  ],
  discard: ["Quitter sans enregistrer ?", "المغادرة دون حفظ؟"],
  leave: ["Quitter", "مغادرة"],
} as const;
export function useCommunicationCopy() {
  const { i18n } = useTranslation();
  const ar = i18n.language.startsWith("ar");
  return (key: string) => copy[key as keyof typeof copy]?.[ar ? 1 : 0] ?? key;
}
export function communicationDate(value: string | null, locale = i18n.language) {
  return value
    ? new Intl.DateTimeFormat(locale.startsWith("ar") ? "ar-MA" : "fr-MA", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date(value))
    : "—";
}
