package com.hiveapp.platform.admin.service;

import com.hiveapp.platform.admin.dto.AdminPermissionSummaryDto;
import com.hiveapp.platform.admin.dto.AdminRolePresetDto;
import com.hiveapp.platform.registry.definition.PermissionGrantValidator;
import com.hiveapp.platform.registry.domain.entity.Permission;
import com.hiveapp.platform.registry.domain.repository.PermissionRepository;
import com.hiveapp.shared.exception.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Component
@RequiredArgsConstructor
public class AdminRolePresetCatalog {

    private static final List<PresetDefinition> DEFINITIONS = List.of(
            new PresetDefinition(
                    "PLATFORM_OBSERVER",
                    "Observateur plateforme",
                    "Consulte l’activité opérationnelle sans pouvoir la modifier.",
                    Set.of(
                            "platform.admin_users.overview",
                            "platform.admin_users.read",
                            "platform.admin_users.read_detail",
                            "platform.admin_users.read_permissions",
                            "platform.roles.read",
                            "platform.roles.read_detail",
                            "platform.roles.read_holders",
                            "platform.roles.read_history",
                            "platform.roles.list_presets",
                            "platform.roles.list_grantable_permissions",
                            "platform.roles.preview_impact",
                            "platform.segments.list",
                            "platform.segments.read_detail",
                            "platform.segments.compare",
                            "platform.segments.read_revisions",
                            "platform.segments.read_history",
                            "platform.segments.count",
                            "platform.segments.preview",
                            "platform.segments.read_activations",
                            "platform.segments.read_activation_audience",
                            "platform.campaigns.list",
                            "platform.campaigns.read",
                            "platform.campaigns.read_operations",
                            "platform.campaigns.compare",
                            "platform.campaigns.revisions",
                            "platform.campaigns.history",
                            "platform.campaigns.preview_schedule",
                            "platform.campaigns.read_audience",
                            "platform.offers.list",
                            "platform.offers.read",
                            "platform.offers.read_operations",
                            "platform.offers.read_editable_definition",
                            "platform.offers.revisions",
                            "platform.offers.compare",
                            "platform.offers.preview_publish",
                            "platform.offers.read_owner",
                            "platform.offers.read_stats",
                            "platform.offers.read_redemptions",
                            "platform.offers.read_redemption_detail",
                            "platform.offers.history",
                            "platform.offers.choose_accounts",
                            "platform.offers.resolve_account_choices",
                            "platform.offers.choose_products",
                            "platform.offers.resolve_product_choices",
                            "platform.offers.choose_quota_resources",
                            "platform.offers.choose_owners",
                            "platform.offers.resolve_owner_choices",
                            "platform.offers.choose_campaigns",
                            "platform.offers.resolve_campaign_choices",
                            "platform.plans.overview",
                            "platform.plans.list",
                            "platform.plans.read_detail",
                            "platform.plans.read_plan_operations",
                            "platform.plans.preview_plan_activation",
                            "platform.plans.list_features",
                            "platform.plans.list_subscribers",
                            "platform.plans.list_add_ons",
                            "platform.plans.read_add_on",
                            "platform.plans.read_add_on_operations",
                            "platform.plans.preview_add_on_activation",
                            "platform.plans.list_quota_packages",
                            "platform.plans.read_quota_package",
                            "platform.plans.read_quota_package_operations",
                            "platform.plans.compare_quota_package",
                            "platform.plans.preview_quota_package_activation",
                            "platform.plans.read_quota_package_history",
                            "platform.price_books.list",
                            "platform.price_books.read",
                            "platform.price_books.read_history",
                            "platform.price_books.preview_activation",
                            "platform.price_books.preview_replacement",
                            "platform.commercial_availability.inspect_compatibility",
                            "platform.commercial_availability.read_history",
                            "platform.commercial_policies.list",
                            "platform.commercial_policies.read",
                            "platform.commercial_policies.read_revisions",
                            "platform.commercial_policies.compare",
                            "platform.commercial_policies.read_history",
                            "platform.commercial_policies.read_activations",
                            "platform.commercial_policies.read_activation_accounts",
                            "platform.commercial_policies.preview_audience",
                            "platform.commercial_policies.preview_activation",
                            "platform.subscriptions.search_accounts",
                            "platform.subscriptions.choose_accounts",
                            "platform.subscriptions.resolve_account_choices",
                            "platform.subscriptions.list_assignable_prices",
                            "platform.subscriptions.choose_add_on_overrides",
                            "platform.subscriptions.choose_quota_package_overrides",
                            "platform.subscriptions.read",
                            "platform.subscriptions.read_changes",
                            "platform.subscriptions.read_lifecycle_actions",
                            "platform.subscriptions.read_lifecycle_history",
                            "platform.billing.list_invoices",
                            "platform.billing.read_invoice",
                            "platform.billing.read_invoice_document",
                            "platform.billing.read_account_identity",
                            "platform.billing.read_payments",
                            "platform.billing.read_account_timeline",
                            "platform.billing.read_account_billing_profile",
                            "platform.billing.list_reconciliation",
                            "platform.billing.list_provider_events",
                            "platform.analytics.read_summary",
                            "platform.analytics.read_financial_series",
                            "platform.analytics.read_subscription_series",
                            "platform.analytics.read_offer_series",
                            "platform.registry.read",
                            "platform.registry.feature_catalog",
                            "platform.registry.permission_catalog",
                            "platform.registry.sync_status",
                            "platform.registry.control_history")),
            new PresetDefinition(
                    "CUSTOMER_OPERATIONS",
                    "Opérations clients",
                    "Consulte les comptes et abonnements et traite les opérations client courantes.",
                    Set.of(
                            "platform.plans.choose_plans",
                            "platform.plans.resolve_plan_choices",
                            "platform.plans.resolve_plan_choice_codes",
                            "platform.plans.choose_add_ons",
                            "platform.plans.resolve_add_on_choices",
                            "platform.plans.resolve_add_on_choice_codes",
                            "platform.plans.choose_quota_packages",
                            "platform.plans.resolve_quota_package_choices",
                            "platform.plans.resolve_quota_package_choice_codes",
                            "platform.plans.read_detail",
                            "platform.plans.read_plan_operations",
                            "platform.plans.read_add_on_operations",
                            "platform.plans.read_quota_package_operations",
                            "platform.plans.list_features",
                            "platform.plans.list_subscribers",
                            "platform.plans.lookup_subscriber_owner_email",
                            "platform.subscriptions.search_accounts",
                            "platform.subscriptions.lookup_account_owner_email",
                            "platform.subscriptions.choose_accounts",
                            "platform.subscriptions.resolve_account_choices",
                            "platform.subscriptions.list_assignable_prices",
                            "platform.subscriptions.choose_add_on_overrides",
                            "platform.subscriptions.choose_quota_package_overrides",
                            "platform.subscriptions.read",
                            "platform.subscriptions.read_changes",
                            "platform.subscriptions.choose_change_options",
                            "platform.subscriptions.preview_change",
                            "platform.subscriptions.apply_change",
                            "platform.subscriptions.cancel_change",
                            "platform.subscriptions.confirm_checkout",
                            "platform.subscriptions.read_lifecycle_actions",
                            "platform.subscriptions.preview_lifecycle",
                            "platform.subscriptions.cancel_at_period_end",
                            "platform.subscriptions.keep_renewing",
                            "platform.subscriptions.cancel_immediately",
                            "platform.subscriptions.suspend",
                            "platform.subscriptions.restore",
                            "platform.subscriptions.extend_grace",
                            "platform.subscriptions.read_lifecycle_history",
                            "platform.billing.list_invoices",
                            "platform.billing.read_invoice",
                            "platform.billing.read_invoice_document",
                            "platform.billing.read_account_identity",
                            "platform.billing.read_payments",
                            "platform.billing.read_account_timeline",
                            "platform.billing.read_account_billing_profile",
                            "platform.billing.update_account_billing_profile",
                            "platform.billing.manual_settlement",
                            "platform.analytics.read_summary",
                            "platform.analytics.read_financial_series",
                            "platform.analytics.read_subscription_series",
                            "platform.analytics.read_operations")),
            new PresetDefinition(
                    "COMMERCIAL_OPERATIONS",
                    "Opérations commerciales",
                    "Gère le catalogue commercial, les offres et les abonnements.",
                    Set.of(
                            "platform.plans.overview",
                            "platform.plans.list",
                            "platform.plans.choose_plans",
                            "platform.plans.resolve_plan_choices",
                            "platform.plans.resolve_plan_choice_codes",
                            "platform.plans.read_detail",
                            "platform.plans.read_plan_operations",
                            "platform.plans.list_features",
                            "platform.plans.list_subscribers",
                            "platform.plans.lookup_subscriber_owner_email",
                            "platform.plans.create",
                            "platform.plans.update",
                            "platform.plans.duplicate",
                            "platform.plans.revise",
                            "platform.plans.transition_status",
                            "platform.plans.preview_plan_activation",
                            "platform.plans.preview_delete",
                            "platform.plans.delete",
                            "platform.plans.assign_feature",
                            "platform.plans.update_feature",
                            "platform.plans.remove_feature",
                            "platform.plans.list_add_ons",
                            "platform.plans.choose_add_ons",
                            "platform.plans.resolve_add_on_choices",
                            "platform.plans.resolve_add_on_choice_codes",
                            "platform.plans.read_add_on",
                            "platform.plans.read_add_on_operations",
                            "platform.plans.create_add_on",
                            "platform.plans.update_add_on",
                            "platform.plans.revise_add_on",
                            "platform.plans.transition_add_on",
                            "platform.plans.preview_add_on_activation",
                            "platform.plans.delete_add_on",
                            "platform.plans.assign_add_on_feature",
                            "platform.plans.update_add_on_feature",
                            "platform.plans.remove_add_on_feature",
                            "platform.plans.list_quota_packages",
                            "platform.plans.choose_quota_packages",
                            "platform.plans.resolve_quota_package_choices",
                            "platform.plans.resolve_quota_package_choice_codes",
                            "platform.plans.read_quota_package",
                            "platform.plans.read_quota_package_operations",
                            "platform.plans.create_quota_package",
                            "platform.plans.revise_quota_package",
                            "platform.plans.compare_quota_package",
                            "platform.plans.preview_quota_package_activation",
                            "platform.plans.lifecycle_quota_package",
                            "platform.plans.read_quota_package_history",
                            "platform.plans.update_quota_package",
                            "platform.plans.delete_quota_package",
                            "platform.price_books.list",
                            "platform.price_books.read",
                            "platform.price_books.read_history",
                            "platform.price_books.create",
                            "platform.price_books.update_draft",
                            "platform.price_books.preview_activation",
                            "platform.price_books.preview_replacement",
                            "platform.price_books.activate",
                            "platform.price_books.pause",
                            "platform.price_books.reactivate",
                            "platform.price_books.revise",
                            "platform.price_books.schedule_replacement",
                            "platform.price_books.archive",
                            "platform.price_books.delete_draft",
                            "platform.commercial_availability.inspect_compatibility",
                            "platform.commercial_availability.preview_plan_policy",
                            "platform.commercial_availability.update_plan_policy",
                            "platform.commercial_availability.preview_add_on_visibility",
                            "platform.commercial_availability.update_add_on_visibility",
                            "platform.commercial_availability.preview_quota_visibility",
                            "platform.commercial_availability.update_quota_visibility",
                            "platform.commercial_availability.read_history",
                            "platform.segments.list",
                            "platform.segments.read_detail",
                            "platform.segments.create",
                            "platform.segments.update_draft",
                            "platform.segments.duplicate",
                            "platform.segments.revise",
                            "platform.segments.compare",
                            "platform.segments.read_revisions",
                            "platform.segments.read_history",
                            "platform.segments.count",
                            "platform.segments.preview",
                            "platform.segments.read_sample_identities",
                            "platform.segments.activate",
                            "platform.segments.archive",
                            "platform.segments.delete_draft",
                            "platform.segments.read_activations",
                            "platform.segments.read_activation_audience",
                            "platform.segments.read_activation_identities",
                            "platform.segments.read_owner",
                            "platform.segments.reassign_owner",
                            "platform.segments.choose_accounts",
                            "platform.segments.resolve_account_choices",
                            "platform.campaigns.list",
                            "platform.campaigns.read",
                            "platform.campaigns.read_operations",
                            "platform.campaigns.create",
                            "platform.campaigns.update",
                            "platform.campaigns.read_editable_definition",
                            "platform.campaigns.duplicate",
                            "platform.campaigns.revise",
                            "platform.campaigns.compare",
                            "platform.campaigns.revisions",
                            "platform.campaigns.history",
                            "platform.campaigns.preview_schedule",
                            "platform.campaigns.schedule",
                            "platform.campaigns.pause",
                            "platform.campaigns.resume",
                            "platform.campaigns.end",
                            "platform.campaigns.archive",
                            "platform.campaigns.delete_draft",
                            "platform.campaigns.owner",
                            "platform.campaigns.reassign_owner",
                            "platform.campaigns.choose_owners",
                            "platform.campaigns.resolve_owner_choices",
                            "platform.campaigns.choose_accounts",
                            "platform.campaigns.resolve_account_choices",
                            "platform.campaigns.choose_segments",
                            "platform.campaigns.resolve_segment_choices",
                            "platform.campaigns.read_audience",
                            "platform.campaigns.read_audience_identities",
                            "platform.offers.list",
                            "platform.offers.read",
                            "platform.offers.read_operations",
                            "platform.offers.read_editable_definition",
                            "platform.offers.preview_create_definition",
                            "platform.offers.preview_update_definition",
                            "platform.offers.create",
                            "platform.offers.update",
                            "platform.offers.duplicate",
                            "platform.offers.revise",
                            "platform.offers.revisions",
                            "platform.offers.compare",
                            "platform.offers.preview_publish",
                            "platform.offers.publish",
                            "platform.offers.retire",
                            "platform.offers.restore",
                            "platform.offers.archive",
                            "platform.offers.delete",
                            "platform.offers.read_owner",
                            "platform.offers.reassign_owner",
                            "platform.offers.read_stats",
                            "platform.offers.read_redemptions",
                            "platform.offers.read_redemption_detail",
                            "platform.offers.read_redemption_identities",
                            "platform.offers.history",
                            "platform.offers.choose_accounts",
                            "platform.offers.resolve_account_choices",
                            "platform.offers.choose_products",
                            "platform.offers.resolve_product_choices",
                            "platform.offers.choose_quota_resources",
                            "platform.offers.choose_owners",
                            "platform.offers.resolve_owner_choices",
                            "platform.offers.choose_campaigns",
                            "platform.offers.resolve_campaign_choices",
                            "platform.offers.preview_for_account",
                            "platform.offers.apply_for_account",
                            "platform.commercial_policies.list",
                            "platform.commercial_policies.read",
                            "platform.commercial_policies.choose_accounts",
                            "platform.commercial_policies.resolve_account_choices",
                            "platform.commercial_policies.choose_segments",
                            "platform.commercial_policies.resolve_segment_choices",
                            "platform.commercial_policies.preview_audience",
                            "platform.commercial_policies.read_revisions",
                            "platform.commercial_policies.compare",
                            "platform.commercial_policies.read_history",
                            "platform.commercial_policies.read_activations",
                            "platform.commercial_policies.read_activation_accounts",
                            "platform.commercial_policies.read_owner",
                            "platform.commercial_policies.create",
                            "platform.commercial_policies.update_draft",
                            "platform.commercial_policies.duplicate",
                            "platform.commercial_policies.revise",
                            "platform.commercial_policies.preview_activation",
                            "platform.commercial_policies.activate",
                            "platform.commercial_policies.pause",
                            "platform.commercial_policies.resume",
                            "platform.commercial_policies.end",
                            "platform.commercial_policies.archive",
                            "platform.commercial_policies.delete_draft",
                            "platform.commercial_policies.reassign_owner",
                            "platform.subscriptions.search_accounts",
                            "platform.subscriptions.lookup_account_owner_email",
                            "platform.subscriptions.choose_accounts",
                            "platform.subscriptions.resolve_account_choices",
                            "platform.subscriptions.list_assignable_prices",
                            "platform.subscriptions.choose_add_on_overrides",
                            "platform.subscriptions.choose_quota_package_overrides",
                            "platform.subscriptions.read",
                            "platform.subscriptions.read_changes",
                            "platform.subscriptions.choose_change_options",
                            "platform.subscriptions.preview_change",
                            "platform.subscriptions.apply_change",
                            "platform.subscriptions.cancel_change",
                            "platform.subscriptions.confirm_checkout",
                            "platform.subscriptions.read_lifecycle_actions",
                            "platform.subscriptions.preview_lifecycle",
                            "platform.subscriptions.cancel_at_period_end",
                            "platform.subscriptions.keep_renewing",
                            "platform.subscriptions.cancel_immediately",
                            "platform.subscriptions.suspend",
                            "platform.subscriptions.restore",
                            "platform.subscriptions.extend_grace",
                            "platform.subscriptions.read_lifecycle_history",
                            "platform.billing.list_invoices",
                            "platform.billing.read_invoice",
                            "platform.billing.read_invoice_document",
                            "platform.billing.read_account_identity",
                            "platform.billing.read_payments",
                            "platform.billing.read_payment_references",
                            "platform.billing.read_account_timeline",
                            "platform.billing.read_account_billing_profile",
                            "platform.billing.update_account_billing_profile",
                            "platform.billing.manual_settlement",
                            "platform.billing.issue_credit",
                            "platform.billing.preview_refund",
                            "platform.billing.create_refund",
                            "platform.billing.record_manual_refund",
                            "platform.billing.list_reconciliation",
                            "platform.billing.list_provider_events",
                            "platform.billing.reconcile_provider_event",
                            "platform.billing.preview_charge_retry",
                            "platform.billing.retry_charge",
                            "platform.analytics.read_summary",
                            "platform.analytics.read_financial_series",
                            "platform.analytics.read_subscription_series",
                            "platform.analytics.read_offer_series",
                            "platform.analytics.read_operations")),
            new PresetDefinition(
                    "ACCESS_ADMINISTRATOR",
                    "Administration des accès",
                    "Gère les opérateurs, les rôles et leurs permissions.",
                    Set.of(
                            "platform.admin_users.overview",
                            "platform.admin_users.read",
                            "platform.admin_users.read_detail",
                            "platform.admin_users.read_permissions",
                            "platform.admin_users.create",
                            "platform.admin_users.rename",
                            "platform.admin_users.change_email",
                            "platform.admin_users.send_email_verification",
                            "platform.admin_users.resend_activation",
                            "platform.admin_users.generate_temporary_access",
                            "platform.admin_users.toggle_active",
                            "platform.admin_users.bulk_set_active",
                            "platform.admin_users.assign_role",
                            "platform.admin_users.remove_role",
                            "platform.admin_users.bulk_assign_role",
                            "platform.admin_users.bulk_resend_activation",
                            "platform.roles.read",
                            "platform.roles.read_detail",
                            "platform.roles.read_holders",
                            "platform.roles.read_history",
                            "platform.roles.list_presets",
                            "platform.roles.list_grantable_permissions",
                            "platform.roles.preview_impact",
                            "platform.roles.create",
                            "platform.roles.create_from_preset",
                            "platform.roles.update",
                            "platform.roles.duplicate",
                            "platform.roles.replace_permissions",
                            "platform.roles.transition_status",
                            "platform.roles.delete",
                            "platform.roles.grant_permission",
                            "platform.roles.revoke_permission")));

    private final PermissionRepository permissionRepository;
    private final PermissionGrantValidator permissionGrantValidator;
    private final AdminMutationAuthorizer adminMutationAuthorizer;

    @EventListener(ApplicationReadyEvent.class)
    @Order(2)
    @Transactional(readOnly = true)
    public void validateAtStartup() {
        DEFINITIONS.forEach(this::resolvePermissions);
    }

    @Transactional(readOnly = true)
    public List<AdminRolePresetDto> availablePresets() {
        AdminMutationAuthorizer.GrantCeiling ceiling = adminMutationAuthorizer.currentActorGrantCeiling();
        return DEFINITIONS.stream()
                .filter(definition -> ceiling.allowsAll(definition.permissionCodes()))
                .map(this::toDto)
                .toList();
    }

    @Transactional(readOnly = true)
    public AdminRolePresetDto requireAvailable(String code) {
        PresetDefinition definition = DEFINITIONS.stream()
                .filter(candidate -> candidate.code().equals(code))
                .findFirst()
                .orElseThrow(() -> new ResourceNotFoundException("AdminRolePreset", "code", code));
        if (!adminMutationAuthorizer.currentActorGrantCeiling().allowsAll(definition.permissionCodes())) {
            throw new com.hiveapp.shared.exception.ForbiddenException(
                    "The acting administrator cannot grant every permission in this preset.");
        }
        return toDto(definition);
    }

    private AdminRolePresetDto toDto(PresetDefinition definition) {
        return new AdminRolePresetDto(
                definition.code(),
                definition.name(),
                definition.description(),
                resolvePermissions(definition).stream().map(AdminRolePresetCatalog::toSummary).toList());
    }

    private List<Permission> resolvePermissions(PresetDefinition definition) {
        Map<String, Permission> byCode = new LinkedHashMap<>();
        permissionRepository.findAllByCodeIn(definition.permissionCodes())
                .forEach(permission -> byCode.put(permission.getCode(), permission));
        return definition.permissionCodes().stream()
                .sorted()
                .map(code -> {
                    Permission permission = byCode.get(code);
                    if (permission == null) {
                        throw new IllegalStateException(
                                "Admin role preset " + definition.code() + " references missing permission " + code);
                    }
                    permissionGrantValidator.requirePlatformAdminRoleGrantable(code);
                    return permission;
                })
                .toList();
    }

    private static AdminPermissionSummaryDto toSummary(Permission permission) {
        return new AdminPermissionSummaryDto(
                permission.getId(),
                permission.getCode(),
                permission.getName(),
                permission.getDescription(),
                permission.getAction(),
                permission.getResource());
    }

    private record PresetDefinition(
            String code,
            String name,
            String description,
            Set<String> permissionCodes
    ) {}
}
